feat: add backoff logic to the SQS Poller
awslabs/aws-dotnet-messaging pull request #107
Opened 2024-03-13 13:39 UTC by philasmar

*Issue #, if available:*
DOTNET-7390

*Description of changes:*
* Create interfaces for IBackoffHandler and IBackoffPolicy
* Add message bus configuration points for specifying the backoff policy, which for now is no backoff, interval backoff or capped exponential backoff
* Implement the 3 backoff policies: No backoff, Interval backoff and Capped Exponential backoff
* Implement the default backoff handler
* Add a sample app that replaces our BackoffHandler with Polly
* Add tests and update docs

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-13 22:03 UTC, ashovlin commented on src/AWS.Messaging/Services/Backoff/BackoffHandler.cs
> +                _logger.LogError(ex, "We have encountered an issue while polling '{SubscriberEndpoint}'.", configuration.SubscriberEndpoint);
nit: Don't love `"we`" since it might be unclear who it is (the application? the framework? the service?)

2024-03-13 22:03 UTC, ashovlin commented on src/AWS.Messaging/Services/Backoff/BackoffHandler.cs
> +                _logger.LogWarning("Attempting to poll SQS for messages once again...");
Could we log the retry count here? It's something that jumps out to me when working the SDK's retries
> "Attempt #{0} to poll for SQS messages"

2024-03-14 02:32 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/IntervalBackoffPolicy.cs
> +    /// <returns>A fixed interval representing the backoff time.</returns>
The interfaces don't care and the implementer can go with any time unit. However, our implementations do care, since the BackoffHandler is doing a TimeSpan.FromMilliseconds(waitTime). I will switch to using seconds all over and I will add docs about the unit we are returning where it makes sense.

2024-03-14 02:38 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/IBackoffHandler.cs
> +/// Interface for a backoff handler that is responsible for performing back-offs in the event that a given delegate throws an exception.
In general, I used "backoff" when it is before "handler" or "policy". I used "back off" for the verb. "back-off" was used for plural because Jetbrains Rider kept complaining about "backoffs" being a typo so I switched to "back-offs". I will keep it as is for now unless you feel strongly about it.

2024-03-14 02:45 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/BackoffHandler.cs
> +                await task.Invoke();
The token is still being passed to the SDK call. If you refer to the `SQSMessagePoller` where we are passing the delegate to the `BackoffHandler`, the SQS call still takes in the cancellation token.
```
var receiveMessageResponse = await _sqsClient.ReceiveMessageAsync(receiveMessageRequest, token);
```

2024-03-14 03:00 UTC, philasmar commented on sampleapps/SubscriberService/Program.cs
> +        });
Good catch. I didn't mean to leave those in. I removed them.

2024-03-14 03:01 UTC, philasmar commented on src/AWS.Messaging/Configuration/BackoffPolicyBuilder.cs
> +/// This builder is used to configure the backoff policy and it's options.
Fixed

2024-03-14 03:01 UTC, philasmar commented on src/AWS.Messaging/Configuration/IBackoffPolicyBuilder.cs
> +/// This builder interface is used to configure the backoff policy and it's options.
Fixed

2024-03-14 03:01 UTC, philasmar commented on src/AWS.Messaging/Configuration/IMessageBusBuilder.cs
> +    /// Configures the backoff policy used by <see cref="BackoffHandler"/> and it's available options.
Fixed

2024-03-14 03:02 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/Options/IntervalBackoffOptions.cs
> +    public int FixedInterval { get; set; } = 1000;
I used ms initially because I thought users might want to use sub-second intervals. Though I do agree that its better for consistency for us to use seconds. I changed it for now, but open to feedback from others.

2024-03-14 03:02 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/IntervalBackoffPolicy.cs
> +    /// <returns>A fixed interval representing the backoff time.</returns>
Done

2024-03-14 03:03 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/BackoffHandler.cs
> +                _logger.LogError(ex, "We have encountered an issue while polling '{SubscriberEndpoint}'.", configuration.SubscriberEndpoint);
Reverted.

2024-03-14 03:03 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/BackoffHandler.cs
> +                _logger.LogWarning("Attempting to poll SQS for messages once again...");
Done

2024-03-14 19:50 UTC, 96malhar commented on src/AWS.Messaging/Configuration/MessageBusBuilder.cs
> +            _messageConfiguration.BackoffPolicy = settings.BackoffPolicy ?? BackoffPolicy.CappedExponential;
You are already checking `settings.BackoffPolicy` for null in the `if` statement above. Not sure if the null-coalescing operator (??) serves any purpose here.

2024-03-14 19:50 UTC, 96malhar commented on src/AWS.Messaging/Services/Backoff/BackoffHandler.cs
> +                _logger.LogWarning("Backing off for {WaitTime}s before trying again...", waitTime);
I think it's worth being explicit in the log message that we are backing off before try to poll messages from SQS. This will help in identifying the action that we are backing off from in-case we add retries to other pieces in MPF

2024-03-14 19:50 UTC, 96malhar commented on src/AWS.Messaging/Services/Backoff/Policies/Options/CappedExponentialBackoffOptions.cs
> +    /// The backoff time in seconds to cap the exponential backoff at.
This should also mention that once this threshold is reached, we will always perform retries at a fixed interval of `CapBackoffTime`.

2024-03-14 19:50 UTC, 96malhar commented on src/AWS.Messaging/Services/Backoff/Policies/Options/CappedExponentialBackoffOptions.cs
> +        if (CapBackoffTime < 0)
Should this be changed to `CapBackoffTime <= 0`. Having a `CapBackoffTime` of 0 does not make sense.

2024-03-14 19:50 UTC, 96malhar commented on src/AWS.Messaging/Services/Backoff/Policies/Options/IntervalBackoffOptions.cs
> +        if (FixedInterval < 0)
Should this be changed to `FixedInterval <= 0`. Having a `FixedInterval ` of 0 does not make sense.

2024-03-14 20:07 UTC, philasmar commented on src/AWS.Messaging/Configuration/MessageBusBuilder.cs
> +            _messageConfiguration.BackoffPolicy = settings.BackoffPolicy ?? BackoffPolicy.CappedExponential;
Even though I am checking for nulls on 249, Rider is still complaining on 251 that the value might be null which is why I added ??.

2024-03-14 20:33 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/BackoffHandler.cs
> +                _logger.LogWarning("Backing off for {WaitTime}s before trying again...", waitTime);
Done

2024-03-14 20:34 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/Options/CappedExponentialBackoffOptions.cs
> +    /// The backoff time in seconds to cap the exponential backoff at.
Done

2024-03-14 20:34 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/Options/CappedExponentialBackoffOptions.cs
> +        if (CapBackoffTime < 0)
I purposefully left in 0 as it is a valid value. A user could turn off backoffs by setting to 0.

2024-03-14 20:34 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/Options/IntervalBackoffOptions.cs
> +        if (FixedInterval < 0)
I purposefully left in 0 as it is a valid value. A user could turn off backoffs by setting to 0.

2024-03-14 23:35 UTC, 96malhar approved these changes

2024-03-15 23:55 UTC, normj requested changes

2024-03-15 23:55 UTC, normj commented on src/AWS.Messaging/Services/Backoff/IBackoffPolicy.cs
> +    bool ShouldBackoff(Exception exception, SQSMessagePollerConfiguration configuration);
For the most part the backoff framework you have here is general purpose so we could use it for anywhere we want to do backoff. If we wanted to add another area in the project that to have backoff would we add a separate `ShouldBackoff` method?

2024-03-15 23:55 UTC, normj commented on src/AWS.Messaging/Services/Backoff/IBackoffHandler.cs
> +    Task BackoffAsync(Func<Task> task, SQSMessagePollerConfiguration configuration, CancellationToken token);
Should we have the `Func` return data? Something like the following would allow you to not have to predeclare the received message variable in the poller and then use it in the closure. Not sure if we would ever have a use case where we don't need to return someting.

```
Task<T> BackoffAsync<T>(Func<Task, T> task, SQSMessagePollerConfiguration configuration, CancellationToken token);
```

2024-03-15 23:55 UTC, normj commented on src/AWS.Messaging/Services/Backoff/IBackoffPolicy.cs
> +    double RetrieveBackoffTime(int numberOfRetries);
Return a `TimeSpan` instead of an ambiguous `double`.

2024-03-15 23:55 UTC, normj commented on src/AWS.Messaging/Services/Backoff/Policies/CappedExponentialBackoffPolicy.cs
> +        var backoffTime = Math.Pow(2, numberOfRetries);
Add some jitter to the backoffTime. Here is how the SDK does jitter.
https://github.com/aws/aws-sdk-net/blob/32f1a09b6f7b8e2f2e9b53332ad82e654927453e/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/StandardRetryPolicy.cs#L241

2024-03-15 23:55 UTC, normj commented on src/AWS.Messaging/Services/Backoff/Policies/Options/CappedExponentialBackoffOptions.cs
> +    public int CapBackoffTime { get; set; } = 3600;
An hour long backoff time is way too long. I would think more like 60 seconds as a default.

Also change the `int` to a `TimeSpan` so the units are not ambiguous. Unless that will make the deserialization from IConfiguration weird.

2024-03-15 23:55 UTC, normj commented on src/AWS.Messaging/Services/Backoff/Policies/Options/IntervalBackoffOptions.cs
> +    public int FixedInterval { get; set; } = 1;
Same comment as above. Use `TimeSpan` unless that makes the deserialization from IConfiguration weird.

2024-03-18 14:24 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/IBackoffPolicy.cs
> +    bool ShouldBackoff(Exception exception, SQSMessagePollerConfiguration configuration);
You can go about this in multiple ways. If your back off logic is dependent on the exception thrown, you would expand your implementation of the `ShouldBackoff` method to account for the different areas that a backoff is needed. However, if your logic is different, it makes sense to implement a new instance of `IBackoffPolicy` and pass it to a new `IBackoffHandler`. You could also do away with the `BackoffPolicy` and handle things differently in a new `IBackoffHandler`.

2024-03-19 15:22 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/IBackoffHandler.cs
> +    Task BackoffAsync(Func<Task> task, SQSMessagePollerConfiguration configuration, CancellationToken token);
Fixed

2024-03-19 15:22 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/IBackoffPolicy.cs
> +    double RetrieveBackoffTime(int numberOfRetries);
Fixed

2024-03-19 15:22 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/CappedExponentialBackoffPolicy.cs
> +        var backoffTime = Math.Pow(2, numberOfRetries);
Fixed

2024-03-19 15:23 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/Options/CappedExponentialBackoffOptions.cs
> +    public int CapBackoffTime { get; set; } = 3600;
I updated the cap to 60 seconds. However I did not change the type to `TimeSpan` as it would make deserialization weird. This is kept consistent with the SQS Poller Configuration options which are all `int`.

2024-03-19 15:23 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/Options/IntervalBackoffOptions.cs
> +    public int FixedInterval { get; set; } = 1;
I did not change the type to `TimeSpan` as it would make deserialization weird. This is kept consistent with the SQS Poller Configuration options which are all `int`.

2024-03-19 18:37 UTC, normj commented on src/AWS.Messaging/Services/Backoff/Policies/Options/IntervalBackoffOptions.cs
> +    public int FixedInterval { get; set; } = 1;
Ok

2024-03-19 18:37 UTC, normj approved these changes

2024-03-19 19:55 UTC, ashovlin commented on src/AWS.Messaging/Services/Backoff/IBackoffHandler.cs
> +/// Interface for a backoff handler that is responsible for performing back-offs in the event that a given delegate throws an exception.
As long as there's some system 👍

2024-03-19 21:55 UTC, ashovlin commented on src/AWS.Messaging/Services/Backoff/Policies/CappedExponentialBackoffPolicy.cs
> +        lock (_randomJitter) {
Could we use `Random.Shared` to avoid needing to roll our own thread safety?

2024-03-19 22:17 UTC, ashovlin commented on src/AWS.Messaging/Services/Backoff/Policies/CappedExponentialBackoffPolicy.cs
> +        var backoffTime = Convert.ToInt32(Math.Min(jitter * Math.Pow(2, numberOfRetries), _options.CapBackoffTime));
Curious about the source of this equation. It doesn't appear to be applying the jitter when we're at the `CapBackoffTime` - so those requests may become predicatable. Is that a concern?

The formula in https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ avoids this by applying the jitter to the outcome of `Math.Min`?

2024-03-19 22:17 UTC, ashovlin commented on src/AWS.Messaging/Services/Backoff/Policies/CappedExponentialBackoffPolicy.cs
> +    private readonly Random _randomJitter = new();
Will this be consistent per host?

From https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/:
> When adding jitter to scheduled work, we do not select the jitter on each host randomly. Instead, we use a consistent method that produces the same number every time on the same host.

2024-03-19 22:17 UTC, ashovlin commented on src/AWS.Messaging/Services/Backoff/Policies/IntervalBackoffPolicy.cs
> +        return TimeSpan.FromSeconds(_options.FixedInterval);
Should we apply jitter here too? If running pollers using the interval policy on a fleet of hosts, is there a chance that that they could synchronize and retry polling at the same time?

>we found that clients frequently send requests on a regular interval, like once per minute. However, when a client has multiple servers behaving the same way, they can line up and trigger their requests at the same time. This can be the first few seconds of a minute, or the first few seconds after midnight for daily jobs. By paying attention to per-second load, and working with clients to jitter their periodic workloads, we accomplished the same amount of work with less server capacity.

2024-03-20 14:42 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/CappedExponentialBackoffPolicy.cs
> +        var backoffTime = Convert.ToInt32(Math.Min(jitter * Math.Pow(2, numberOfRetries), _options.CapBackoffTime));
I am now applying jitter to `Math.Min`

2024-03-20 14:43 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/CappedExponentialBackoffPolicy.cs
> +    private readonly Random _randomJitter = new();
I don't believe so based on the implementation of `Random.Shared`. I will wait for customer feedback on this and see if we need to worry about it.

2024-03-20 14:44 UTC, philasmar commented on src/AWS.Messaging/Services/Backoff/Policies/IntervalBackoffPolicy.cs
> +        return TimeSpan.FromSeconds(_options.FixedInterval);
I applied jitter to the interval policy as well.

2024-03-20 15:09 UTC, ashovlin approved these changes

2024-03-20 16:32 UTC, merged