add beacon to the docs site
awslabs/aws-dotnet-messaging pull request #113
Opened 2024-03-23 06:19 UTC by atqy

*Issue #, if available:*
None

*Description of changes:*
Add beacon functionality to the docs website.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-28 13:17 UTC, philasmar commented
These changes are causing a weird behavior of the site. Also there is weird text in the top left part of the site.
![image](https://github.com/awslabs/aws-dotnet-messaging/assets/53088140/dba1081a-282c-4a4d-9ea3-b48ccec3c7d6)

2024-03-28 13:18 UTC, philasmar requested changes
These changes are causing a weird behavior of the site. You can scroll the site up or down indefinitely whether there is or isn't any content. Also there is weird text in the top left part of the site.
![image](https://github.com/awslabs/aws-dotnet-messaging/assets/53088140/80b57f20-37d1-41f7-b2ee-c031f6e2e66d)

2024-04-19 14:39 UTC, philasmar reviewed
The changes look good. Please rebase your branch on top of the `dev` branch.

2024-04-22 16:25 UTC, philasmar approved these changes

2024-04-24 19:01 UTC, ashovlin approved these changes

2024-04-24 19:06 UTC, merged