fix: Correctly deserialize outer envelope when processing messages relayed through EventBridge
awslabs/aws-dotnet-messaging pull request #114
Opened 2024-03-25 22:12 UTC by 96malhar

*Description of changes:* 
This is a sample SQS message when messages are forwarded by EventBridge
```
{
  "version": "0",
  "id": "961ac8a3-a4ee-0e17-d8d9-36c81ae29955",
  "detail-type": "AWS.Messaging.IntegrationTests.Models.ChatMessage",
  "source": "/aws/messaging",
  "account": "000000000",
  "time": "2024-03-25T20:39:11Z",
  "region": "us-west-2",
  "resources": [],
  "detail": {
    "id": "526d5466-5f51-42ce-a64b-8a220a7f1b71",
    "source": "/aws/messaging",
    "specversion": "1.0",
    "type": "AWS.Messaging.IntegrationTests.Models.ChatMessage",
    "time": "2024-03-25T20:39:10.8491344+00:00",
    "data": "{\"MessageDescription\":\"Test1\"}"
  }
}
```

The `detail` property is sent as a JSON object and not as a string. Invoking [JsonElement.GetString](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement.getstring?view=net-8.0) on this node throws an `InvalidOperationException`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-25 23:15 UTC, normj requested changes

2024-03-25 23:15 UTC, normj commented on src/AWS.Messaging/Serialization/EnvelopeSerializer.cs
> +            return propertyValue.ToString();
Can we be more exact, I'm worried we could get some surprise from the `ToString()` method. Something like the following.

```
            if (propertyValue.ValueKind == JsonValueKind.String)
                return propertyValue.GetString();
            else if (propertyValue.ValueKind == JsonValueKind.Object)
                return propertyValue.GetRawText();
            else
                throw new Exception("Some invalid format with the right exception");
```

2024-03-25 23:36 UTC, 96malhar commented on src/AWS.Messaging/Serialization/EnvelopeSerializer.cs
> +            return propertyValue.ToString();
Done

2024-03-25 23:39 UTC, normj approved these changes

2024-03-26 14:07 UTC, philasmar approved these changes

2024-03-26 16:39 UTC, ashovlin approved these changes

2024-03-26 16:54 UTC, merged