[UA update] chore: Update User-Agent string
awslabs/aws-dotnet-messaging pull request #127
Opened 2024-04-12 03:27 UTC by 96malhar

*Issue #, if available:*
SDK-169882

*Description of changes:*
chore: Update User-Agent string

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-15 15:00 UTC, ashovlin approved these changes

2024-04-15 15:54 UTC, philasmar requested changes

2024-04-15 15:54 UTC, philasmar commented on cb641346-f9f6-414d-be09-90ea0b8366a7.json
This file needs to be located in the directory `.autover/changes`. If you try and create the file with the tool, it'll automatically create it in the proper directory.

2024-04-15 15:54 UTC, philasmar commented on cb641346-f9f6-414d-be09-90ea0b8366a7.json
> +          "chore: Update User-Agent string"
The changelog messages in this file are supposed to be user-friendly messages, not commit messages. You shouldn't use conventional commit messages format in here.

2024-04-15 16:12 UTC, 96malhar commented on cb641346-f9f6-414d-be09-90ea0b8366a7.json
Done

2024-04-15 16:13 UTC, 96malhar commented on cb641346-f9f6-414d-be09-90ea0b8366a7.json
> +          "chore: Update User-Agent string"
Fixed

2024-04-16 19:07 UTC, philasmar approved these changes

2024-04-16 19:11 UTC, merged