return the result from the publisher to the caller.
awslabs/aws-dotnet-messaging pull request #130
Opened 2024-04-16 08:07 UTC by robvanpamel

*Description of changes:*

When a message fails from eventbridge, the error result was not shown. This could lead to some issues in the future. 
I adapted this so the errormessage and if required the errorcode can be retrieved 

As the publisher is abstracted across EventBridge, SQS and SNS I had to make some sacrifices for naming; event <-> message. 
Please have a look at it and provide some feedback so it can be adapted where you need it. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-16 23:10 UTC, normj commented
For SNS and SQS a user would need to catch exceptions and for EventBridge they would need to check the response which is likely to be forgotten. For example we forgot to think about it. I believe EventBridge's `PutEvents` API does the HTTP 200 with errors pattern because it supports batch event publishing. Since we are only sending a single event I wonder if we should have the EventBridge publisher check if response for failure and then we should throw a Messaging exception. Update the other publishers to also throw the same Messaging exception wrapping the SDK's exception. What do you think?

If we decide to support the batch flow in the future we can handle that threw separate APIs.

2024-04-17 05:52 UTC, robvanpamel commented
I agree to create a separate API for batch processing in the future. 
So to continue, we keep the existing `IPublishResponse ` to return a messageid / eventid but remove the ErrorMessage from it. I do think the messageid is required as a lot of people use this. At least on my 2 previous projects we had this in place. 

For returning the errormessage to the user with eventbridge, we check the response and throw a Message Exception. Let's call it `FailedToPublishException`. ( Like the others it would inherit from `AWSMessagingException`) 

For the other publishers SQS and SNS, we catch the exceptions and wrap it with the same `FailedToPublishException`.  
Do you mind if the existing exceptions, eg `InvalidMessageException` would be wrapped in the `FailedToPublishException` as an innerexception as well (https://github.com/awslabs/aws-dotnet-messaging/blob/main/src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs )? That way it can be easily implemented.

2024-04-17 23:00 UTC, normj commented
I agree we should have the `IPublishResponse` with `MessageId`. I'm preferring `MessageId` over `EventId` since we are calling this our messaging library.

Yes to your logic for checking the response from event bridge and throw `FailedToPublishException` exception if there is a failure.

All publishers should throw `FailedToPublishException` and the XML docs for the publish method should indicate that with the `<exception>` tag. For SQS and SNS it will wrap the service exception. The `FailedToPublishException` exception when only be for for if the service call fails in some way. The `InvalidMessageException` is for bad configuration and I don't think should be wrapped in the `FailedToPublishException`.

2024-04-18 07:12 UTC, robvanpamel commented
I made the requested changes, let me know if there are things you would like to change

2024-04-18 18:41 UTC, normj requested changes

2024-04-18 18:41 UTC, normj commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublishResponse.cs
> +    public string? ErrorCode { get; set; }
Since an exception will always be thrown if there is an `ErrorCode` users will never get a response with `ErrorCode` and `ErrorMessage` set. I think we should remove them from the response to avoid confusion.

2024-04-18 18:41 UTC, normj commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs
> +                    throw new InvalidPublisherEndpointException($"Unable to determine a destination event bus for message of type '{typeof(T)}'.");
Good catch

2024-04-18 18:41 UTC, normj commented on src/AWS.Messaging/Publishers/SNS/SNSPublishResponse.cs
> +    public string? ErrorMessage { get; set; }
I don't think this is ever set and can be removed.

2024-04-18 18:41 UTC, normj commented on src/AWS.Messaging/Publishers/SQS/SQSSendResponse.cs
> +    public string? ErrorMessage { get; set; }
Not set and can be removed.

2024-04-18 19:06 UTC, robvanpamel commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublishResponse.cs
> +    public string? ErrorCode { get; set; }
yes, sorry I forgot to remove these !

2024-04-18 19:23 UTC, robvanpamel commented
Changes are done. I did had some issues in GIT so the local history looks strange. But I assume you can squash it, so that does not causes issues. 
Let me know if you see something else!

2024-04-18 19:33 UTC, normj approved these changes

2024-04-18 19:34 UTC, normj commented
Thanks @robvanpamel. Don't worry about the commits, we will squash when we merge. The PR looks good to me. Let me get another team member on the team to review it.

2024-04-18 19:53 UTC, ashovlin commented on src/AWS.Messaging/Exceptions.cs
> +public class EventBridgePutEventsException : Exception
Can this subclass `AWSMessagingException`? I think we use that to distinguish between framework-owned vs. "external" exceptions at some points.

2024-04-18 19:53 UTC, ashovlin commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublishResponse.cs
> +    /// Gets and sets the property EventId.
Minor, could you update the doc comment to match `MessageId`?

2024-04-18 19:53 UTC, ashovlin commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs
> +                    throw new FailedToPublishException("Message failed to publish.", ex);
Could this follow the same pattern as the other two, where `AmazonEventBridgeException` is the special case? 

If there's a reason why this is different (is this the 200 with errors case?), could you add that context as a comment?

2024-04-18 20:11 UTC, philasmar commented on src/AWS.Messaging/Exceptions.cs
> +/// Thrown if the EventBridgePublishResponse contains a message with an errorcode
nit: use a doc reference for EventBridgePublishResponse
nit: separate "errorcode"

2024-04-18 20:11 UTC, philasmar commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublishResponse.cs
> +///
nit: remove empty whitespace

2024-04-18 20:12 UTC, philasmar commented
Could you please rebase your PR on top of `dev`?
Also, could you please follow https://github.com/awslabs/aws-dotnet-messaging/blob/dev/CONTRIBUTING.md in order to add a `change file` in your PR?

2024-04-19 06:16 UTC, robvanpamel commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs
> +                    throw new FailedToPublishException("Message failed to publish.", ex);
I did this to make sure that other exception thrown by the AWS SDK which were not from the aws-dotnet-messaging framework were wrapped inside the FailedToPublishException. Since errors will show up in the error code it can be changed I assume. I don't know the internals of the EventBridge SDK very well. 

I changed it now as you requested.

2024-04-19 06:57 UTC, robvanpamel commented
I rebased, added the change file and pointed to dev iso main

2024-04-19 13:03 UTC, philasmar approved these changes

2024-04-19 14:13 UTC, ashovlin approved these changes

2024-04-22 14:03 UTC, robvanpamel commented
Is any action from my side required to integrate this into the next release?

2024-04-22 15:59 UTC, merged

2024-04-22 16:00 UTC, normj commented
@robvanpamel Your side is good. We just need schedule a release to include your change. Thanks for the PR.

2024-04-22 21:24 UTC, normj commented
Version `0.9.1` is out with this PR. Thanks again for the contribution.