feat: Add Lambda message pump service
awslabs/aws-dotnet-messaging pull request #40
Opened 2023-04-27 14:18 UTC by 96malhar

*Issue #, if available:*
DOTNET-6879

*Description of changes:*
This PR adds the Lambda message pump service to process messages from an SQS queue

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-01 07:53 UTC, normj requested changes
Sorry I haven't done a full review but wanted to pass along some feedback to unblock you.

2023-05-01 07:53 UTC, normj commented on src/AWS.Messaging/Configuration/IMessageBusBuilder.cs
> +    IMessageBusBuilder AddLambdaMessagePoller(string queueUrl, Action<LambdaMessagePollerOptions>? options = null);
We should not have to pass in the `queueUrl`. We can compute the `queueUrl` from the incoming Lambda event from the `eventSourceARN` attribute.

2023-05-01 07:53 UTC, normj commented on src/AWS.Messaging/Lambda/LambdaMessagePump.cs
> +        await task.ContinueWith(completedPollerTask =>
Why bury the exception? Seems like you should just `await` the `lambdaMessagePoller.StartPollingAsync(stoppingToken)` statement.

2023-05-01 07:53 UTC, normj commented on src/AWS.Messaging/Lambda/LambdaMessagePump.cs
> +        await task.ContinueWith(completedPollerTask =>
Same comment as above about awaiting `lambdaMessagePoller.StartPollingAsync(stoppingToken)`

2023-05-01 07:53 UTC, normj commented on src/AWS.Messaging/Lambda/LambdaMessagePoller.cs
> +            QueueUrl = _configuration.SubscriberEndpoint
This value should be coming from the incoming Lambda event.

2023-05-01 07:53 UTC, normj commented on src/AWS.Messaging/Lambda/LambdaMessagePoller.cs
> +        var sqsEvent = _configuration.SQSEvent;
The Lambda function's themselves are configured for how many messages that want to be sent into them. That is their batch size. We should just assume that want the whole batch size processed in parallel and send all the messages into the manager after doing the conversion.

2023-05-01 07:53 UTC, normj commented on src/AWS.Messaging/Configuration/LambdaMessagePollerOptions.cs
> +public class LambdaMessagePollerOptions
I'm pretty sure this class can go away after my comments in the `LambdaMessagePoller` are processed.

2023-05-01 07:53 UTC, normj commented on src/AWS.Messaging/Configuration/LambdaMessagePollerConfiguration.cs
> +    public const int DEFAULT_MAX_NUMBER_OF_CONCURRENT_MESSAGES = 10;
The amount of concurrent messages in Lambda's case should just the function's configured batch size. These 2 properties can a way after my comment in the poller is addressed.

2023-05-01 07:53 UTC, normj commented on src/AWS.Messaging/Configuration/LambdaMessagePollerConfiguration.cs
> +    public LambdaMessagePollerConfiguration(string queueUrl)
The QueueUrl should just come from the `SQSEvent`

2023-05-01 07:53 UTC, normj commented on src/AWS.Messaging/Lambda/LambdaMessagePump.cs
> +        var pollerConfiguration = _messageConfiguration.GetLambdaMessagePollerConfiguration(sqsQueueUrl);
I don't like this design of getting the `LambdaMessagePollerConfiguration` from the DI and then mutating that instance. Config coming from DI in general should be immutable.

Just seems like we should be creating a local options instances and then passing that into the execute method.

2023-05-02 14:41 UTC, philasmar requested changes

2023-05-02 14:41 UTC, philasmar commented on src/AWS.Messaging/Configuration/LambdaMessagePollerConfiguration.cs
> +/// Internal configuration  while working with AWS Lambda to process messages from SQS
nit: remove double spacing between "configuration  while"

2023-05-02 14:41 UTC, philasmar commented on src/AWS.Messaging/Configuration/MessageBusBuilder.cs
> +            // since the LambdaMessagePollerConfiguration object is created at runtime
you said "since" twice

2023-05-02 14:41 UTC, philasmar commented on src/AWS.Messaging/Configuration/MessageBusBuilder.cs
> +            // since the LambdaMessagePollerConfiguration object is created at runtime
add a doc reference to "LambdaMessagePollerConfiguration" instead of hard-coding it

2023-05-02 14:41 UTC, philasmar commented on src/AWS.Messaging/Lambda/ILambdaMessagePump.cs
> +    /// Invokes the underlying <see cref="IMessagePoller"/> to process SQS messages. All messages that are successfull processed will be deleted from the SQS queue.
nit: typo in "successfull". Should be "successfully"

2023-05-02 14:41 UTC, philasmar commented on src/AWS.Messaging/Lambda/LambdaMessagePoller.cs
> +        await Task.WhenAll(taskList);
Shouldn't we be doing exception handling here?

2023-05-02 14:41 UTC, philasmar commented on src/AWS.Messaging/Lambda/LambdaMessagePoller.cs
> +            var batchItemFailures = _configuration.SQSBatchResponse!.BatchItemFailures;
can we handle this better, instead of using the null-forgiving operator?

2023-05-02 14:41 UTC, philasmar commented on src/AWS.Messaging/Lambda/LambdaMessagePoller.cs
> +                var messageID = message.SQSMetadata?.MessageID ?? throw new InvalidDataException($"message envelope with ID '{message.Id}' contains an null SQS message ID");
nit: "an null" should be "a null"

2023-05-02 14:41 UTC, philasmar commented on src/AWS.Messaging/Lambda/LambdaMessagePump.cs
> +        // Mark all messages as failed initially. Messages that are successfully process will be removed from the list.
nit: "process" should be "processed"

2023-05-02 14:41 UTC, philasmar commented on src/AWS.Messaging/Lambda/LambdaMessagePump.cs
> +        var sqsQueueUrl = await GetSQSQueueUrl(sqsQueueArn);
we should do some exception handling here

2023-05-02 16:18 UTC, ashovlin requested changes

2023-05-02 16:18 UTC, ashovlin commented on src/AWS.Messaging/Lambda/LambdaMessagePoller.cs
> +                var index = batchItemFailures.FindIndex(x => string.Equals(x.ItemIdentifier, messageID));
Commented on the pre-population of this list, but I still don't understand the motivation for this approach. Seems like we're spending unnecessary time managing this list and opening ourselves up to indexing-related bugs, as well as cluttering the trace logs.

Why not store a list of just failures, in a thread-safe collection if necessary?

2023-05-02 16:18 UTC, ashovlin commented on src/AWS.Messaging/Lambda/LambdaMessagePoller.cs
> +    }
This appears to be a lot of copy and pasted code - can we consolidate either in a utilities class or a base class for SQS pollers?

2023-05-02 16:18 UTC, ashovlin commented on src/AWS.Messaging/Lambda/LambdaMessagePoller.cs
> +    }
Same comment as above about consolidating across all SQS pollers.

2023-05-02 18:50 UTC, ashovlin commented on src/AWS.Messaging/AWS.Messaging.csproj
> +    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="2.1.0" />
Fine if not in this PR, but should we explore Norm's comment from today about considering a separate package for Lambda:
* Lambda subscribers won't have to resolve EventBridge and SNS
* Publishers and non-Lambda subscribers won't have to resolve SQSEvents

2023-05-02 18:51 UTC, ashovlin commented on src/AWS.Messaging/Lambda/LambdaMessagePoller.cs
> +                var index = batchItemFailures.FindIndex(x => string.Equals(x.ItemIdentifier, messageID));
Can you improve commenting on this approach with what you explained in the 5/2 sync call?

2023-05-03 21:17 UTC, 96malhar commented on src/AWS.Messaging/Lambda/LambdaMessagePump.cs
> +        // Mark all messages as failed initially. Messages that are successfully process will be removed from the list.
I had initally taken this approach because there was no way for the `DefaultMessageManager` to signal the underlying `IMessagePoller` when a particular message could not processed. However, in the latest revision, I have introduced a new method on `IMessagePoller` called `HandleMessageProcessingFailureAsync`.

This method is invoked by the `DefaultMessageManager` incase the message could not be processed successfully. In the `LambdaMessagePoller`, when batch failure reporting is enabled, this method adds the messageID to the `BatchItemFailures` collection in a thread safe manner. This way we are only including messages that were failed to process and no longer need to pre-populate this list.

2023-05-03 21:17 UTC, 96malhar commented on src/AWS.Messaging/Lambda/LambdaMessagePump.cs
> +        var queueName = arnSegments[arnSegments.Length - 1];
Fixed. I have also modified this method to resolve the queue URL from the ARN without making the SQS service call.

2023-05-03 21:17 UTC, 96malhar commented on src/AWS.Messaging/Lambda/LambdaMessagePump.cs
> +        var response = await _sqsClient.GetQueueUrlAsync(queueName);
I have modified this method to resolve the queue URL from the ARN using string manipulation without making the SQS service call.

2023-05-03 21:21 UTC, 96malhar commented
> 1. Can this target a feature branch until at least unit tests are added?
> 2. Can you add sample applications in this PR? It'd be helpful to see how all of this is configured from the user's perspective during review.

I have targeted my branch to a feature branch for now. I'd prefer to get approvals on the approach that I am taking and then proceed to add unit tests.

I have added a sample Lambda function that uses the proposed design to process messages.

2023-05-13 23:15 UTC, normj commented
Closing this PR because I started a fair amount of rework separating Lambda into a separate project and other refactoring. I think it will just be easier to start a fresh PR.

2023-05-13 23:15 UTC, closed without merging