Update SQSPoller's visibility timeout handling to only extend the expiration for messages that are within the configured threshold
awslabs/aws-dotnet-messaging pull request #42
Opened 2023-05-04 16:57 UTC by ashovlin

*Issue #, if available:* DOTNET-6901

*Description of changes:* This refines the SQSPoller's handling of the visibility timeout for in flight messages, per design #39.
* **Before:** The manager would extend the visibility timeout of _all_ in flight messages, at a configured internal.
* **After:** The manager will extend the visibility timeout of in flight messages that are within a configured threshold of expiring (`VisibilityTimeoutExtensionThreshold`), which it evaluated at a configured heartbeat interval (`VisibilityTimeoutExtensionHeartbeatInterval`).

**Internal note:** I also introduced `MessageManagerConfiguration`. The `DefaultMessageManager` increasingly needed access to its `IMessagePoller`'s configuration, which we had been mirroring as public properties on the poller. Right now the manager configuration is a one-time copy of the poller's configuration for shared options. The new manager configuration object is not customizable by users, but I think it does help us with testing as well as give us a path towards supporting a many-to-one poller-to-manager relationship in the future.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-04 23:55 UTC, normj requested changes

2023-05-04 23:55 UTC, normj commented on src/AWS.Messaging/Configuration/MessageManagerConfiguration.cs
> +    public class MessageManagerConfiguration
Can we make the type `Internal` so we can avoid this type showing up in intellisense.

2023-05-04 23:55 UTC, normj commented on src/AWS.Messaging/Configuration/SQSMessagePollerConfiguration.cs
> +    /// How frequently the framework will check in flight messages and extend the the visibility
You have double `the the`.

2023-05-04 23:55 UTC, normj commented on src/AWS.Messaging/SQSMetadata.cs
> +        internal DateTimeOffset? ExpectedVisibilityTimeoutExpiration { get; set; }
This feels weird to put this transitory state on the message envelope only used in message manager. I think we should maintain this state inside the message manager. Maybe a separate dictionary in the manager that is keyed off message id to a state object that contains the `ExpectedVisibilityTimeoutExpiration`.

2023-05-08 15:17 UTC, philasmar commented on src/AWS.Messaging/Configuration/MessageManagerConfiguration.cs
> +namespace AWS.Messaging.Configuration
nit: can you use top level statements

2023-05-08 15:17 UTC, philasmar commented on src/AWS.Messaging/SQS/SQSMessagePoller.cs
> +            _logger.LogError("Attempted to track the expected visibility timout of message {MessageId} without SQS metadata.", message.Id);
nit: typo in "timout"

2023-05-08 15:17 UTC, philasmar commented on src/AWS.Messaging/SQS/SQSMessagePoller.cs
> +            message.SQSMetadata.ExpectedVisibilityTimeoutExpiration = message.SQSMetadata.ApproximateFirstReceiveTimestamp + TimeSpan.FromSeconds(newVisibilityTimeoutWindowSeconds);
is `message.SQSMetadata.ApproximateFirstReceiveTimestamp` also Utc time?

2023-05-09 22:22 UTC, ashovlin commented on src/AWS.Messaging/Configuration/MessageManagerConfiguration.cs
> +    public class MessageManagerConfiguration
I added a TODO for now. I agree, but currently it ripples out because the `ActivatorUtilities.CreateInstance<DefaultMessageManager>` call in the factory relies on the public constructor, which can't take an `internal` parameter. I'd rather revisit visibility in a dedicated PR.

2023-05-09 22:24 UTC, ashovlin commented on src/AWS.Messaging/Configuration/SQSMessagePollerConfiguration.cs
> +    /// How frequently the framework will check in flight messages and extend the the visibility
Oops, fixed.

2023-05-09 22:24 UTC, ashovlin commented on src/AWS.Messaging/Configuration/MessageManagerConfiguration.cs
> +namespace AWS.Messaging.Configuration
Done.

2023-05-09 22:24 UTC, ashovlin commented on src/AWS.Messaging/SQS/SQSMessagePoller.cs
> +            _logger.LogError("Attempted to track the expected visibility timout of message {MessageId} without SQS metadata.", message.Id);
Oops, fixed.

2023-05-09 22:24 UTC, ashovlin commented on src/AWS.Messaging/SQS/SQSMessagePoller.cs
> +            throw new MissingSQSMetadataException($"Attempted to track the expected visibility timout of message {message.Id} without SQS metadata.");
Oops, fixed.

2023-05-09 22:25 UTC, ashovlin commented on src/AWS.Messaging/SQS/SQSMessagePoller.cs
> +            message.SQSMetadata.ExpectedVisibilityTimeoutExpiration = message.SQSMetadata.ApproximateFirstReceiveTimestamp + TimeSpan.FromSeconds(newVisibilityTimeoutWindowSeconds);
This property went away in the new commit which moved the timing metadata to DefaultMessageManager internals per https://github.com/awslabs/aws-dotnet-messaging/pull/42#discussion_r1185604827.

2023-05-09 22:26 UTC, ashovlin commented on src/AWS.Messaging/SQSMetadata.cs
> +        internal DateTimeOffset? ExpectedVisibilityTimeoutExpiration { get; set; }
Added `InFlightMetadata` to store both the visibility timings as well as the handler task, which `DefaultMessageManager` now maintains a concurrent dictionary of.

2023-05-09 22:30 UTC, ashovlin commented
Added a new commit today, which largely focused on https://github.com/awslabs/aws-dotnet-messaging/pull/42#discussion_r1185604827 about tracking the visibility timeout timing internally as opposed on the the `MessageEnvelope.SQSMetadata`.

Other changes in this diff:
* Realized I misunderstood `ApproximateFirstReceiveTimestamp`, which appears to be truly for the first receive, and is not changed on subsequent receives for the same message. The initial expected visibility timeout window is now based on `UtcNow` shortly after receiving the message.
* `DefaultMessageManager` has a large diff to existing tests, but it was to make them more concise by introducing extension methods for `VerifyDeleteMessagesAsyncWasCalledWith`, `VerifyInvokeAsyncWasCalledWith`, etc.

2023-05-10 16:42 UTC, philasmar approved these changes

2023-05-11 14:16 UTC, merged