feat: add ability to configure message source or compute it as a fallback
awslabs/aws-dotnet-messaging pull request #45
Opened 2023-05-10 15:36 UTC by philasmar

*Issue #, if available:*
DOTNET-6903

*Description of changes:*
* Added the ability for users to configure the message source in the message bus
* If a value is not configured, the source will be computed based on the compute environment the process is running in.
* Added a design doc that explains the behavior implemented in this PR.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-10 23:44 UTC, normj requested changes

2023-05-10 23:44 UTC, normj commented on docs/design/message-source-computation-design.md
> +**Resolved Source** - `/AmazonECSTask/{TASK-ARN}`
I'm wondering if we should add the cluster name to put a name that is more permanent then a task which can be transitory. What would you think of 

`/AmazonECS/{cluster-name}/{task-arn}`

2023-05-10 23:44 UTC, normj commented on docs/design/message-source-computation-design.md
> +**Resolved Source** - `/AWSLambdaFunction/{FUNCTION-NAME}`
Based on my comment about ECS where the source could have multiple I think we can have the prefix be just the service. Replace `/AWSLambdaFunction` with `/AWSLambda`

2023-05-10 23:44 UTC, normj commented on docs/design/message-source-computation-design.md
> +**Resolved Source** - `/AmazonEC2Instance/{INSTANCE-ID}`
Based on my comment about ECS where the source could have multiple I think we can have the prefix be just the service. Replace `/AmazonEC2Instance` with `/AmazonEC2`

2023-05-10 23:44 UTC, normj commented on src/AWS.Messaging/Configuration/IMessageBusBuilder.cs
> +    IMessageBusBuilder AddMessageSource(Uri messageSource);
Can we also have a `AddMessageSourceSuffix` for users that want to add additional data but would like to keep in place the auto computed value?

2023-05-10 23:44 UTC, normj commented on src/AWS.Messaging/Services/IMessageSourceHandler.cs
> +    /// The following compute environments are considered, in the specified order below:
Since this is the interface and not the implementation you might want to say this is the default search path.

2023-05-10 23:44 UTC, normj commented on src/AWS.Messaging/Serialization/EnvelopeSerializer.cs
> +            Source = _messageConfiguration.Source ?? await _messageSourceHandler.ComputeMessageSource(),
The `ComputeMessageSource` call is an expensive call and won't change between messages. So we should make sure we are only calling this once.

2023-05-10 23:44 UTC, normj commented on src/AWS.Messaging/Services/MessageSourceHandler.cs
> +        _messageConfiguration.Source = new Uri(messageSource, UriKind.Relative);
That is a weird side effect behavior here that update the config and return back the computed source. It doesn't seem like that should be the responsibility of the `IMessageSourceHandler` to handle the caching as well. That would mean custom implementations of `IMessageSourceHandler` would also have to know they need to update the `_messageConfiguration.Source` field.

2023-05-10 23:44 UTC, normj commented on src/AWS.Messaging/Services/MessageSourceHandler.cs
> +    private string TryGetSourceFromLambda()
`Try` methods have a specific expected pattern in .NET. They should follow something like:

`bool TryXXX(<optional-key-parameter>, out <type> output)`.

If you don't want to follow that pattern that is fine but don't prefix the methods with `Try`. You can just call them `Get` methods that can return back null. In that case I would have them methods return `string?` and stop returning back empty string if not value was found.

2023-05-10 23:44 UTC, normj commented on src/AWS.Messaging/Services/MessageSourceHandler.cs
> +        var ecsMetadataURI = _environmentManager.GetEnvironmentVariable("ECS_CONTAINER_METADATA_URI");
Put the looking up the `ECS_CONTAINER_METADATA_URI` variable inside the `ECSContainerMetadataManager` type. This class doesn't need to know the details of looking up ECS data.

2023-05-11 14:05 UTC, ashovlin commented on docs/design/message-source-computation-design.md
> +The Amazon ECS container agent injects an environment variable called `ECS_CONTAINER_METADATA_URI` into each container in aN ECS task. To retrieve the metadata related to an ECS task we can issue a G
nit: Typo in `aN`

2023-05-11 14:13 UTC, ashovlin commented on src/AWS.Messaging/Services/DnsManager.cs
> +    public string GetHostName() => Dns.GetHostName();
Docs say this can throw a `SocketException` - should we be more defensive?

2023-05-14 02:43 UTC, philasmar commented on docs/design/message-source-computation-design.md
> +The **Source** attribute is stored at the `MessageConfiguration` level and will be passed to the `MessageEnvelope` irrespective of the type of message being published. An extension method is provided
Done

2023-05-14 02:44 UTC, philasmar commented on docs/design/message-source-computation-design.md
> +In case access to the `Source` attribute is needed, the attribute can be found on the `MessageConfiguration` object which is accessible through the dependency injection framework by injecting `IMessa
Done

2023-05-14 02:44 UTC, philasmar commented on docs/design/message-source-computation-design.md
> +**Resolved Source** - `/AmazonECSTask/{TASK-ARN}`
Done

2023-05-14 02:44 UTC, philasmar commented on docs/design/message-source-computation-design.md
> +**Resolved Source** - `/AWSLambdaFunction/{FUNCTION-NAME}`
Done

2023-05-14 02:44 UTC, philasmar commented on docs/design/message-source-computation-design.md
> +**Resolved Source** - `/AmazonEC2Instance/{INSTANCE-ID}`
Done

2023-05-14 02:44 UTC, philasmar commented on src/AWS.Messaging/Configuration/IMessageBusBuilder.cs
> +    IMessageBusBuilder AddMessageSource(Uri messageSource);
Done

2023-05-14 02:45 UTC, philasmar commented on src/AWS.Messaging/Services/IMessageSourceHandler.cs
> +    /// The following compute environments are considered, in the specified order below:
Removed the implementation detail from the interface and added it on the implementation class method.

2023-05-14 02:45 UTC, philasmar commented on src/AWS.Messaging/Serialization/EnvelopeSerializer.cs
> +            Source = _messageConfiguration.Source ?? await _messageSourceHandler.ComputeMessageSource(),
Done

2023-05-14 02:45 UTC, philasmar commented on src/AWS.Messaging/Services/MessageSourceHandler.cs
> +        _messageConfiguration.Source = new Uri(messageSource, UriKind.Relative);
Done

2023-05-14 02:45 UTC, philasmar commented on src/AWS.Messaging/Services/MessageSourceHandler.cs
> +    private string TryGetSourceFromLambda()
Removed the `Try` and used `Get`

2023-05-14 02:46 UTC, philasmar commented on src/AWS.Messaging/Services/MessageSourceHandler.cs
> +        var ecsMetadataURI = _environmentManager.GetEnvironmentVariable("ECS_CONTAINER_METADATA_URI");
Done

2023-05-14 02:46 UTC, philasmar commented on docs/design/message-source-computation-design.md
> +The Amazon ECS container agent injects an environment variable called `ECS_CONTAINER_METADATA_URI` into each container in aN ECS task. To retrieve the metadata related to an ECS task we can issue a G
Fixed

2023-05-14 02:46 UTC, philasmar commented on src/AWS.Messaging/Services/DnsManager.cs
> +    public string GetHostName() => Dns.GetHostName();
Agreed. I left this class as is because I want it to closely resemble the `Dns` class, but I added exception handling on the caller method.

2023-05-16 00:14 UTC, normj requested changes

2023-05-16 00:14 UTC, normj commented on src/AWS.Messaging/Services/MessageSourceHandler.cs
> +            return new Uri($"{_messageConfiguration.Source}{_messageConfiguration.SourceSuffix}", UriKind.Relative);
I think we should enforce there is a `/` in between source and source suffix. Also we should make sure there is not `//` if both source ends with a `/` and suffix starts with `/`.

2023-05-16 00:14 UTC, normj commented on src/AWS.Messaging/Services/MessageSourceHandler.cs
> +        return new Uri($"{messageSource}{_messageConfiguration.SourceSuffix}", UriKind.Relative);
For the utility method you create for making sure there is one and only one `/` between source and suffix use here as well.

2023-05-17 14:35 UTC, philasmar commented on src/AWS.Messaging/Services/MessageSourceHandler.cs
> +            return new Uri($"{_messageConfiguration.Source}{_messageConfiguration.SourceSuffix}", UriKind.Relative);
Done

2023-05-17 18:49 UTC, normj approved these changes

2023-05-18 19:33 UTC, ashovlin approved these changes

2023-05-18 19:37 UTC, merged