Add support for .NET Lambda functions subscribers to MPF
awslabs/aws-dotnet-messaging pull request #48
Opened 2023-05-15 07:19 UTC by normj

*Description of changes:*
This PR adds a new `AWS.Messaging.Lambda` as a plugin for `AWS.Messaging` allowing Lambda functions to be subscribers.

To use Lambda as a subscriber users would add this NuGet package and then during DI setup add a call `AddLambdaMessageProcessor` to inject the Lambda specific services.
```
[LambdaStartup]
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddAWSMessageBus(builder =>
        {
            builder.AddMessageHandler<OrderHandler, OrderInfo>();

            builder.AddLambdaMessageProcessor(options =>
            {
                options.MaxNumberOfConcurrentMessages = 4;
            });
        });
    }
}
```

To support plugins like `AWS.Messaging.Lambda` I added the `AddAdditionalService` method to `IMessageBusBuilder` so plugins could include their own services.

The Lambda functions themselves just need to inject an instance of `ILambdaMessaging` and then call either `ProcessLambdaEventAsync` or `ProcessLambdaEventWithBatchResponseAsync` depending whether function is configured for partial failure or not.
```
[LambdaFunction(Policies = "AWSLambdaSQSQueueExecutionRole")]
public async Task<SQSBatchResponse> FunctionHandler([FromServices] ILambdaMessaging messaging, SQSEvent evnt, ILambdaContext context)
{
    return await messaging.ProcessLambdaEventWithBatchResponseAsync(evnt, context);
}
```

Things to note for reviewers:
* There is no polling in Lambda since the service itself did the polling. I removed the SQS operations from `IMessagePoller` and put them in `ISQSMessageCommunication`. The `SQSMessagePoller` implements both `IMessagePoller` and `ISQSMessageCommunication`. This allowed for Lambda case to have `DefaultLambdaMessageProcessor` that implements `ISQSMessageCommunication` along with its own `ILambdaMessageProcessor` and Lambda doesn't have any forced polling symantics. The `IMessageManager` now works with the `ISQSMessageCommunication` instead of the `IMessagePoller`.
* It is important to make `ILambdaContext` accessible to the `IMessageHandler` so I made it an injectable service. That is done with the `LambdaContextServiceHolder` service. Hopefully the comments in there are clear how the mechanism works.
* To support scenarios where the .NET logging is not configured in the DI I added `TryAdd` for the null implementations so that the DI injections should still be satisfied. I ran into this with Lambda because the DI is naked by default.

I wanted to get some reviews on the PR but I plan on adding more tests and filling in the new README file with descriptions for the Lambda configuration options.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-18 15:20 UTC, philasmar requested changes
Github is also reporting warnings around nullability for this PR. Could you please have a look at those?

2023-05-18 15:20 UTC, philasmar commented on src/AWS.Messaging.Lambda/Services/DefaultLambdaMessageProcessor.cs
> +                throw new MissingSQSMetadataException($"Attempted to delete message {message.Id} from {_configuration.SubscriberEndpoint} without an SQS receipt handle.");
If 1 message was problematic then we will throw an exception and not continue looping over the other messages. Are we intentionally aborting the Deletion of a number of messages if 1 of those mesasges are problematic?

2023-05-18 15:20 UTC, philasmar commented on src/AWS.Messaging.Lambda/Services/ILambdaMessageProcessor.cs
> +    /// and if partial failure is enabled returns a SQSBatchResponse.
nit: add docs reference for `SQSBatchResponse`

2023-05-18 15:20 UTC, philasmar commented on src/AWS.Messaging.Lambda/Services/Internal/LambdaContextServiceHolder.cs
> +/// LambdaContextServiceHolder is used as a singleton service in the DI that holds onto the current ILambdaContext for the request. The
nit: avoid using `LambdaContextServiceHolder` in the description to account for renaming in the future.

2023-05-18 15:20 UTC, philasmar commented on src/AWS.Messaging.Lambda/Services/Internal/LambdaContextServiceHolder.cs
> +/// LambdaContextServiceHolder is used as a singleton service in the DI that holds onto the current ILambdaContext for the request. The
add docs reference for `ILambdaContext`

2023-05-18 15:20 UTC, philasmar commented on src/AWS.Messaging.Lambda/Services/Internal/LambdaContextServiceHolder.cs
> +    /// The current ILambdaContext for the function invocation.
add docs reference for `ILambdaContext`

2023-05-18 15:20 UTC, philasmar commented on src/AWS.Messaging.Lambda/Services/LambdaMessageProcessorConfiguration.cs
> +    /// For Lambda functions that are configured for partial failure and return an SQSBatchResponse this property is ignored.
nit: add docs reference for `SQSBatchResponse`

2023-05-18 15:20 UTC, philasmar commented on src/AWS.Messaging/Configuration/IMessageBusBuilder.cs
> +    /// Add additional services to the IMessageBusBuilder. This method is used for AWS.Messaging plugins to add services for messaging.
nit: add doc reference to `IMessageBusBuilder`

2023-05-18 15:20 UTC, philasmar commented on src/AWS.Messaging/SQS/ISQSMessageCommunication.cs
> +    /// <param name="token">Optional token to cancel the deletion.</param>
the cancellation token is for report message failure and not deletion here

2023-05-18 21:48 UTC, normj commented on sampleapps/LambdaMessaging/Function.cs
> +    /// This function returns an SQSBatchResponse to support partial batch failure.
Done

2023-05-18 21:52 UTC, normj commented on src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs
> +        var sqsQueueArn = sqsEvent.Records[0].EventSourceArn;
I added a check in the entry point public methods that there has to be at least one record otherwise do a quick return.

2023-05-18 21:52 UTC, normj commented on src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs
> +            // TODO: This will value should be set differently when working with FIFO queues.
Done

2023-05-18 21:53 UTC, normj commented on src/AWS.Messaging.Lambda/Exceptions.cs
> +/// Thrown when an <see cref="LambdaMessagingOptions" /> is configured with one or more invalid values
Done

2023-05-18 21:54 UTC, normj commented on src/AWS.Messaging.Lambda/ILambdaMessaging.cs
> +/// invoke one of the process methods passing the SQSEvent and ILambdaContext.
Done

2023-05-18 22:00 UTC, normj commented on src/AWS.Messaging.Lambda/LambdaMessagingOptions.cs
> +    /// to false the messages will be deleted by the Lambda service if all of the messages in the were successfully processed
I reworked this comment block

2023-05-18 22:00 UTC, normj commented on src/AWS.Messaging.Lambda/LambdaMessagingOptions.cs
> +    /// For Lambda functions that are configured for partial failure and return an SQSBatchResponse this property is ignored.
Done

2023-05-18 22:01 UTC, normj commented on src/AWS.Messaging.Lambda/README.md
> +In AWS Lambda the Lambda service takes care of reading the messages from the SQS queue. This plugin allows the messages in the incoming Lambda event to be feed
Done

2023-05-18 22:02 UTC, normj commented on src/AWS.Messaging.Lambda/README.md
> +to pass in the `SQSEvent` sent in by the Lambda service. If you Lambda function is configured for partial failure response use the
Fixed

2023-05-18 22:07 UTC, normj commented on src/AWS.Messaging.Lambda/Services/DefaultLambdaMessageProcessor.cs
> +                throw new MissingSQSMetadataException($"Attempted to delete message {message.Id} from {_configuration.SubscriberEndpoint} without an SQS receipt handle.");
This is block is is after all of the messages have been loop through and the task's complete. I didn't put any logic to fail fast if a message handler fails abort any current running tasks. I'm on the fence what is the right behavior here and will look for community input. 

My thinking is we might as well try and complete as much as possible. No matter what the user has to deal with a partial amount of messages might have been completed. If they use the `DeleteMessagesWhenCompleted` property then the completed messages would have been deleted. The feedback might be that we should set `DeleteMessagesWhenCompleted` to true by default.

2023-05-18 22:08 UTC, normj commented on src/AWS.Messaging.Lambda/Services/ILambdaMessageProcessor.cs
> +    /// and if partial failure is enabled returns a SQSBatchResponse.
Done

2023-05-18 22:10 UTC, normj commented on src/AWS.Messaging.Lambda/Services/Internal/LambdaContextServiceHolder.cs
> +/// LambdaContextServiceHolder is used as a singleton service in the DI that holds onto the current ILambdaContext for the request. The
Done

2023-05-18 22:10 UTC, normj commented on src/AWS.Messaging.Lambda/Services/Internal/LambdaContextServiceHolder.cs
> +    /// The current ILambdaContext for the function invocation.
Done

2023-05-18 22:14 UTC, normj commented on src/AWS.Messaging.Lambda/Services/Internal/LambdaContextServiceHolder.cs
> +        messageBusBuilder.AddAdditionalService(new ServiceDescriptor(typeof(ILambdaContext), provider =>
We don't currently have new `scopes` being created in the framework so if I used it today it would always return back the same value. In practice for this example `transit` and `scope` are basically the same because we are just returning back the instances from the `Context` property of the singleton `LambdaContextServiceHolder`. Once we have scoped implemented we could revisit this but it won't make a material difference.

2023-05-18 22:14 UTC, normj commented on src/AWS.Messaging.Lambda/Services/LambdaMessageProcessorConfiguration.cs
> +/// Configuration for the <see cref="ILambdaMessageProcessor"/> to use for processing the SQSEvent coming for the Lambda service.
Done

2023-05-18 22:15 UTC, normj commented on src/AWS.Messaging.Lambda/Services/LambdaMessageProcessorConfiguration.cs
> +    /// For Lambda functions that are configured for partial failure and return an SQSBatchResponse this property is ignored.
Done

2023-05-18 22:16 UTC, normj commented on src/AWS.Messaging/Configuration/IMessageBusBuilder.cs
> +    /// Add additional services to the IMessageBusBuilder. This method is used for AWS.Messaging plugins to add services for messaging.
Done

2023-05-18 22:16 UTC, normj commented on src/AWS.Messaging/SQS/ISQSMessageCommunication.cs
> +/// Provides APIs for the IMessageManager to communicate back to SQS the status of a Message.
Done

2023-05-18 22:17 UTC, normj commented on src/AWS.Messaging/SQS/ISQSMessageCommunication.cs
> +    /// Report back to the communication implementer when a message .failed to be processed.
Fixed

2023-05-18 22:18 UTC, normj commented on src/AWS.Messaging/SQS/ISQSMessageCommunication.cs
> +    /// <param name="token">Optional token to cancel the deletion.</param>
Fixed

2023-05-18 22:19 UTC, normj commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +    /// <param name="sqsMessageCommunication">Provides APIs to communicate back to SQS and the associated Queue for me incoming messages.</param>
Fixed

2023-05-19 18:11 UTC, philasmar approved these changes

2023-05-19 18:11 UTC, philasmar commented on sampleapps/LambdaMessaging/Function.cs
> +
nit: remove 1 new line

2023-05-19 18:11 UTC, philasmar commented on sampleapps/LambdaMessaging/Function.cs
> +    /// Creates an instance and injects the ILambdaMessaging service
nit: add docs reference for `ILambdaMessaging`

2023-05-19 18:11 UTC, philasmar commented on sampleapps/LambdaMessaging/Function.cs
> +    /// Lambda function that sends the incoming Lambda SQS Event into the .NET Message Framework.
nit: we've been using "AWS Message Processing Framework for .NET" instead of ".NET Message Framework". Let's try and be consistent on the naming.

2023-05-19 18:11 UTC, philasmar commented on src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs
> +        if (sqsEvent.Records?.Any() == false)
what if `sqsEvent.Records` is null. Wouldn't the if statement be false and we wouldn't return?
maybe switch to `if (!sqsEvent.Records?.Any() ?? true)`?

2023-05-19 18:11 UTC, philasmar commented on src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs
> +        if (sqsEvent.Records?.Any() == false)
what if `sqsEvent.Records` is null. Wouldn't the if statement be false and we wouldn't return?
maybe switch to `if (!sqsEvent.Records?.Any() ?? true)`?

2023-05-19 18:11 UTC, philasmar commented on src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs
> +        }
nit: this could be simplified to `options ??= new LambdaMessagingOptions();`
This is stylistic so you don't need to change it if you don't like it

2023-05-20 02:08 UTC, normj commented on sampleapps/LambdaMessaging/Function.cs
> +
Done

2023-05-20 02:09 UTC, normj commented on sampleapps/LambdaMessaging/Function.cs
> +    /// Creates an instance and injects the ILambdaMessaging service
Done

2023-05-20 02:09 UTC, normj commented on src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs
> +        if (sqsEvent.Records?.Any() == false)
Done

2023-05-20 02:09 UTC, normj commented on sampleapps/LambdaMessaging/Function.cs
> +    /// Lambda function that sends the incoming Lambda SQS Event into the .NET Message Framework.
Done

2023-05-20 02:14 UTC, normj commented on src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs
> +        if (sqsEvent.Records?.Any() == false)
If `sqsEvent.Records` is null then the left side of the `==` evaluates to `false`. That doesn't short circuit the whole expression because the left side will still be compared to the right side of the `==`.  Since both sides evaluate to `false` we would do an early exit.

2023-05-20 02:15 UTC, normj commented on src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs
> +        if (sqsEvent.Records?.Any() == false)
If `sqsEvent.Records` is null then the left side of the `==` evaluates to `false`. That doesn't short circuit the whole expression because the left side will still be compared to the right side of the `==`.  Since both sides evaluate to `false` we would do an early exit.

2023-05-20 02:15 UTC, normj commented on src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs
> +        }
Done

2023-05-20 02:15 UTC, normj commented on src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs
> +        }
Done

2023-05-22 01:36 UTC, ashovlin approved these changes

2023-05-22 01:36 UTC, ashovlin commented on src/AWS.Messaging/Configuration/MessageManagerConfiguration.cs
> +    /// Indicates whether extending message visibility is supported.
nit: _"extending visibility **timeout**"_ in the comment, since just "visibility" may mean the inverse.

2023-05-22 01:36 UTC, ashovlin commented on src/AWS.Messaging/Services/IMessageManagerFactory.cs
> +    public IMessageManager CreateMessageManager(ISQSMessageCommunication sqlMessageCommunication, MessageManagerConfiguration configuration)
nit: `sqlMessageCommunication` -> `sqsMessageCommunication`?

2023-05-22 05:30 UTC, normj commented on src/AWS.Messaging/Configuration/MessageManagerConfiguration.cs
> +    /// Indicates whether extending message visibility is supported.
fixed

2023-05-22 05:31 UTC, normj commented on src/AWS.Messaging/Services/IMessageManagerFactory.cs
> +    public IMessageManager CreateMessageManager(ISQSMessageCommunication sqlMessageCommunication, MessageManagerConfiguration configuration)
Fixed

2023-05-22 06:45 UTC, merged