chore: Register message handlers as scoped dependencies in the servic…
awslabs/aws-dotnet-messaging pull request #49
Opened 2023-05-26 00:13 UTC by 96malhar

*Issue #, if available:*
DOTNET-6957

*Description of changes:*
This PR registers message handlers as scoped dependencies in the service collection.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-26 05:06 UTC, normj requested changes

2023-05-26 05:06 UTC, normj commented on test/AWS.Messaging.UnitTests/HandlerInvokerTests.cs
> +        serviceCollection.AddSingleton(greeterMock.Object);
This test isn't actually confirming that a scope was created. As far as this is concern everything could be added as transient.

IGreeter should be added as a scoped service. Then your `GreetingHandler` you should inject the `IServiceProvider` and see if multiple calls for `GetRequiredService` on `IGreeter` are the same instance but a second invoke of the handler returns back different instance of `IGreeter`.

2023-05-26 17:47 UTC, 96malhar commented on test/AWS.Messaging.UnitTests/HandlerInvokerTests.cs
> +        serviceCollection.AddSingleton(greeterMock.Object);
Done

2023-05-26 18:17 UTC, normj requested changes

2023-05-26 18:17 UTC, normj commented on test/AWS.Messaging.UnitTests/HandlerInvokerTests.cs
> +        var greeter1 = serviceProvider.GetRequiredService<IGreeter>();
This check should be inside the handler. You are testing the scope of the unit test not of the handler. Put this logic in the constructor of the `GreetingHandler` and then use the handlerInvoker from here.

Your handler should be exercising the ideas of a scope service but it is currently not doing anything different then a transient dependency would do.

2023-05-26 18:44 UTC, 96malhar commented on test/AWS.Messaging.UnitTests/HandlerInvokerTests.cs
> +        var greeter1 = serviceProvider.GetRequiredService<IGreeter>();
Moved the check to the constructor of the `GreetingHandler` :thumbsup:

2023-05-26 19:44 UTC, normj approved these changes

2023-05-26 19:50 UTC, ashovlin approved these changes

2023-05-26 19:58 UTC, merged

2023-07-04 08:52 UTC, danielmarbach commented on src/AWS.Messaging/Services/HandlerInvoker.cs
> +        using (var scope = _serviceProvider.CreateScope())
The more future-proof version of this would be to create an [async scope](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceproviderserviceextensions.createasyncscope).