test: Add integration tests to exercise the Lambda subscriptions
awslabs/aws-dotnet-messaging pull request #52
Opened 2023-06-01 15:53 UTC by ashovlin

*Issue #, if available:* DOTNET-6922

*Description of changes:* Adds integration tests that create actual SQS queues mapped to Lambda functions.

The technique here was lifted from https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/test/Amazon.Lambda.RuntimeSupport.Tests/Amazon.Lambda.RuntimeSupport.IntegrationTests, where we're packaging the Lambda code via an msbuild target, and then deploying it during the test setup.

The majority of this is the scaffolding, right now the tests are just testing etiher a single successful or single failing message against `ProcessLambdaEventAsync` and  `ProcessLambdaEventWithBatchResponseAsync`. But it's easier to iterate on tests now that the setup is in place, so open to feedback!

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-06 02:12 UTC, normj requested changes
Just did a brief pass but wanted to give you feedback about removing the msbuild target.

2023-06-06 02:12 UTC, normj commented on test/AWS.Messaging.IntegrationTests/AWS.Messaging.IntegrationTests.csproj
> +  <Target Name="PackageTestFunction" AfterTargets="AfterBuild" Condition="$(PackageTestLambdas)">
I have actually been wanting to take trick this out of Amazon.Lamda.RuntimeSupport. It makes the dev cycle slow because every time you want to do a build even if it hasn't nothing to do with this you have to do this whole step which is slow. I would recommend migrating this flow into the `LambdaIntegrationTestFixture` test fixture so it is only done when a user wants to run the integ tests.

2023-06-06 23:12 UTC, normj requested changes

2023-06-06 23:12 UTC, normj commented on test/AWS.Messaging.Tests.Common/AWSUtilities.cs
> +            await iamClient.AttachRolePolicyAsync(new AttachRolePolicyRequest
Can you add a retry around this in case the role hasn't propagated yet. 10 seconds works most of the time but sometimes it can take longer.

2023-06-06 23:12 UTC, normj commented on test/AWS.Messaging.Tests.Common/AWSUtilities.cs
> +        await Task.Delay(5000);
You can pole the function status to see if it is active yet. That will be more reliable then just a sleep. Here is some code that does the polling. https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/LambdaUtilities.cs#L877

2023-06-19 19:19 UTC, ashovlin commented
Converted to draft until I find time to rework https://github.com/awslabs/aws-dotnet-messaging/pull/52#discussion_r1218779978, other reviewers can hold off for now.

2023-09-07 17:32 UTC, closed without merging