Added fatal checker configuration option in SQSMessagePollerOptions
awslabs/aws-dotnet-messaging pull request #62
Opened 2023-10-15 08:35 UTC by madhub

*Issue #, if available:*
#56 

*Description of changes:*

Currently [SQSMessagePoller](https://github.com/awslabs/aws-dotnet-messaging/blob/d826b7934268942a5c81b19e7aeacf3ba5794d2d/src/AWS.Messaging/SQS/SQSMessagePoller.cs#L127) only checks "InvalidAddress" and "AccessDenied" decided whether to continue polling or rethrow the exception. This is not sufficient , example "QueueDoesNotExistException" exception also should stop the polling.

Better design option would be provide extensibility in SQSMessagePollerOptions that can take user supplied function to decide when top stop polling

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-16 15:17 UTC, ashovlin commented on src/AWS.Messaging/Configuration/SQSMessagePollerConfiguration.cs
> +        "AccessDenied"      // Returned with insufficient IAM permissions to read from the configured queue
Feel free to add `QueueDoesNotExistException` in here. Sorry for not replying to #56 sooner, but I agree it should be in the default error list.

2023-10-16 15:17 UTC, ashovlin commented on src/AWS.Messaging/Configuration/SQSMessagePollerConfiguration.cs
> +    public Func<AmazonSQSException, bool> FatalErrorChecker { get; set; } = IsSQSExceptionFatal;
Suggestion to clean up documentation and naming:
```suggestion
    /// Function that indicates whether an <see cref="AmazonSQSException"/> should stop the poller or continue.
    /// </summary>
    public Func<AmazonSQSException, bool> IsSQSExceptionFatal { get; set; } = IsSQSExceptionFatal;
```

2023-10-19 23:06 UTC, ashovlin commented
One more spot to add the new configuration, can you copy it from the `SQSMessagePollerOptions` to the `SQSMessagePollerConfiguration` here:
https://github.com/awslabs/aws-dotnet-messaging/blob/d826b7934268942a5c81b19e7aeacf3ba5794d2d/src/AWS.Messaging/Configuration/MessageBusBuilder.cs#L119-L126

It's a little awkward, but we arrived here because the queueURL is configured outside of the `Action<SQSMessagePollerOptions>` since it's the primary/required input.

2023-10-19 23:07 UTC, ashovlin requested changes
One more spot to add the new configuration, can you copy it from the `SQSMessagePollerOptions` to the `SQSMessagePollerConfiguration` here:
https://github.com/awslabs/aws-dotnet-messaging/blob/d826b7934268942a5c81b19e7aeacf3ba5794d2d/src/AWS.Messaging/Configuration/MessageBusBuilder.cs#L119-L126

It's a little awkward, but we arrived here because the queueURL is configured outside of the `Action<SQSMessagePollerOptions>` since it's the primary/required input.

2023-10-20 16:09 UTC, ashovlin approved these changes

2023-10-20 21:24 UTC, normj approved these changes
Thanks for the PR!

2023-10-26 15:19 UTC, merged