Initial Benchmark Application
awslabs/aws-dotnet-messaging pull request #63
Opened 2023-10-17 16:20 UTC by ashovlin

*Issue #, if available:* DOTNET-7181

*Description of changes:*
Adds a console application that collects some performance benchmarks for both SQS publishing and the SQS poller.

Inspired by (and grateful for) a similar technique in https://github.com/MassTransit/MassTransit-Benchmark/ and
https://github.com/justeattakeaway/JustSaying/tree/main/tests/JustSaying.Benchmark

To run in Visual Studio, replace the queue URL in `launchSettings.json` with an actual one and press play. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-25 15:33 UTC, ashovlin commented on test/AWS.Messaging.Benchmarks/Program.cs
> +            getDefaultValue: () => false);
From internal team discussion, we want to flips this to `true` by default.

2023-10-26 15:03 UTC, philasmar requested changes
Overall, could you please make sure to document all public classes and attributes?

2024-01-12 15:20 UTC, ashovlin commented on test/AWS.Messaging.Benchmarks/Program.cs
> +        var rootCommand = new RootCommand("Sample app for System.CommandLine");
Done in https://github.com/awslabs/aws-dotnet-messaging/pull/63/commits/e2931cc2558581d9a103b0961c7ba62a049d6e84

2024-01-12 15:20 UTC, ashovlin commented on test/AWS.Messaging.Benchmarks/BenchmarkMessage.cs
> +}
Done in https://github.com/awslabs/aws-dotnet-messaging/pull/63/commits/e2931cc2558581d9a103b0961c7ba62a049d6e84

2024-01-12 15:20 UTC, ashovlin commented on test/AWS.Messaging.Benchmarks/BenchmarkCollector.cs
> +    public BenchmarkCollector(int expectedNumberOfMessages)
Done in https://github.com/awslabs/aws-dotnet-messaging/pull/63/commits/e2931cc2558581d9a103b0961c7ba62a049d6e84

2024-01-12 15:20 UTC, ashovlin commented on test/AWS.Messaging.Benchmarks/BenchmarkCollector.cs
> +    readonly Stopwatch _stopwatch;
Done in https://github.com/awslabs/aws-dotnet-messaging/pull/63/commits/e2931cc2558581d9a103b0961c7ba62a049d6e84

2024-01-12 15:20 UTC, ashovlin commented on test/AWS.Messaging.Benchmarks/BenchmarkCollector.cs
> +public class BenchmarkCollector : IBenchmarkCollector
Done in https://github.com/awslabs/aws-dotnet-messaging/pull/63/commits/e2931cc2558581d9a103b0961c7ba62a049d6e84

2024-01-12 15:20 UTC, ashovlin commented on test/AWS.Messaging.Benchmarks/Program.cs
> +            getDefaultValue: () => false);
Done in https://github.com/awslabs/aws-dotnet-messaging/pull/63/commits/e2931cc2558581d9a103b0961c7ba62a049d6e84

2024-01-12 19:49 UTC, normj approved these changes
Looks good. Just added one suggestion but fine if you don't want to do it.

2024-01-12 19:49 UTC, normj commented on test/AWS.Messaging.Benchmarks/AWS.Messaging.Benchmarks.csproj
> +    <TargetFramework>net6.0</TargetFramework>
Going forward it would probably be better to target .NET 8 for benchmarking. I suspect any perf improvements we make in the underlying SDK will be more for the .NET 8 target.

2024-01-12 20:27 UTC, philasmar approved these changes

2024-01-16 18:11 UTC, ashovlin commented on test/AWS.Messaging.Benchmarks/AWS.Messaging.Benchmarks.csproj
> +    <TargetFramework>net6.0</TargetFramework>
Done, and it took my a few more commits to add .NET 8 to the CI setups.

2024-01-16 21:49 UTC, merged