feat: Enable publishing to FIFO endpoints via IMessagePublisher
awslabs/aws-dotnet-messaging pull request #64
Opened 2023-10-18 01:25 UTC by 96malhar

*Issue #, if available:*
DOTNET-7234

*Description of changes:*
This PR adds the ability to publish message to FIFO queues/topics via the `IMessagePublisher`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-18 17:30 UTC, normj approved these changes

2023-10-18 20:35 UTC, ericsampson commented on src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs
> +            request.MessageGroupId = Guid.NewGuid().ToString();
I thought that for FIFO, if there isn't a natural MessageGroupId then you need to send a fixed value.
If you send a random value like this, then you've entirely defeated the intended FIFO behavior AFAIK.
Or do I just need more coffee

2023-10-18 20:35 UTC, ericsampson commented on src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs
> +            request.MessageGroupId = Guid.NewGuid().ToString();
cc @normj

2023-10-18 21:18 UTC, normj commented on src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs
> +            request.MessageGroupId = Guid.NewGuid().ToString();
My thinking is if a user is not sending a group id the user doesn't care about the order for that message and then they can easily use the `IMessagePublisher` interface. I wanted to make the default experience just work. When they do care about order then inject the `ISQSMessagePublisher`.  Keeping the experience with FIFO queues flexible.

My train of thought is not every message sent to a FIFO queue needs to be ordered. SQS is designed for a group of messages being ordered not the entire queue. I wouldn't want this library to use a fixed group id for all messages allowing no parallelization of message processing. Fine if the user's use case requires all messages be processed in FIFO and use a single group id and in that case they would be working with the `ISQSMessagePublisher`.

A valid question is by having this change, does it make the fact that messages are being sent in as unordered surprising and should we force every user that uses the a FIFO queue always use the `ISQSMessagePublisher`.

2023-10-19 14:53 UTC, philasmar approved these changes

2023-10-20 02:39 UTC, normj requested changes

2023-10-20 02:39 UTC, normj commented on src/AWS.Messaging/Publishers/MessageRoutingPublisher.cs
> +        var errorMessage = $"The generic {nameof(IMessagePublisher)} cannot be used to publish to FIFO endpoints. ";
You should tell the user to use either the ISQS... or ISNS... and they need to set the group id. Use the error message to tell the user what they should do.

2023-10-20 02:39 UTC, normj commented on src/AWS.Messaging/Publishers/MessageRoutingPublisher.cs
> +            errorMessage += $"Refer to the following sample application on how to use {nameof(ISQSPublisher)} to publish to FIFO queues: {fifoPublisherSampleAppUrl}";
Don't have error messages refer to a sample. The code will live forever but the sample and their locations will likely change. I don't want a to consider our samples part of our breaking change ruleset.

2023-10-20 02:39 UTC, normj commented on src/AWS.Messaging/Publishers/MessageRoutingPublisher.cs
> +        var errorMessage = $"The generic {nameof(IMessagePublisher)} cannot be used to publish to FIFO endpoints. ";
I would suggest moving this check into the individual `ISQSMessagePublisher` and `ISNSMessagePublisher` so that if the uses those interfaces but still doesn't provide the group id they get the error message.

2023-10-20 06:38 UTC, 96malhar commented on src/AWS.Messaging/Publishers/MessageRoutingPublisher.cs
> +        var errorMessage = $"The generic {nameof(IMessagePublisher)} cannot be used to publish to FIFO endpoints. ";
Done

2023-10-20 06:38 UTC, 96malhar commented on src/AWS.Messaging/Publishers/MessageRoutingPublisher.cs
> +            errorMessage += $"Refer to the following sample application on how to use {nameof(ISQSPublisher)} to publish to FIFO queues: {fifoPublisherSampleAppUrl}";
Fixed.

2023-10-20 06:40 UTC, 96malhar commented on test/AWS.Messaging.IntegrationTests/SNSPublisherTests.cs
> +        await Task.CompletedTask;
Resolving since we've altered course.

2023-10-20 06:40 UTC, 96malhar commented on src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs
> +            request.MessageGroupId = Guid.NewGuid().ToString();
Resolving since we've altered course.

2023-10-20 17:22 UTC, normj approved these changes

2023-10-20 18:49 UTC, philasmar approved these changes

2023-10-20 20:07 UTC, ashovlin requested changes

2023-10-20 20:07 UTC, ashovlin commented on src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs
> +                $"Additionaly, {nameof(SNSOptions.MessageDeduplicationId)} must also be specified if content based de-duplication is not enabled on the topic.";
nit: typo in "Additionally" (below in SQS publisher too)

2023-10-20 20:12 UTC, 96malhar commented on src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs
> +                $"Additionaly, {nameof(SNSOptions.MessageDeduplicationId)} must also be specified if content based de-duplication is not enabled on the topic.";
Fixed

2023-10-20 20:13 UTC, ashovlin approved these changes

2023-10-20 20:33 UTC, 96malhar commented on src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs
> +            request.MessageGroupId = Guid.NewGuid().ToString();
Thanks  @ericsampson for leaning in. We discussed this internally and concluded that injecting random GUIDs for the message group ID might surprise users that their messages are not being processed in order. We are now throwing an exception when a user is trying to publish a message without a message group ID. The exception message informs the user on how to specify message group IDs (and other FIFO publishing tokens) as part of the publish request.

2023-10-20 20:35 UTC, merged

2023-10-21 16:22 UTC, ericsampson commented on src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs
> +            request.MessageGroupId = Guid.NewGuid().ToString();
thanks all! <3