feat: Add support for FIFO handling of messages
awslabs/aws-dotnet-messaging pull request #66
Opened 2023-10-26 04:25 UTC by 96malhar

*Issue #, if available:*
DOTNET-7235

*Description of changes:*
This PR adds support for correct FIFO handling of messages.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-26 05:14 UTC, normj requested changes

2023-10-26 05:14 UTC, normj commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +        UpdateActiveMessageCount(-1);
This seems like it should be wrapped in a `finally` block so we know for sure It is decremented.

2023-10-26 05:14 UTC, normj commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +        UpdateActiveMessageCount(-1);
This seems like it should be wrapped in a `finally` block so we know for sure It is decremented.

2023-10-26 05:14 UTC, normj commented on src/AWS.Messaging/Services/InFlightMetadata.cs
> -    /// <summary>
Can you provide some context why this was removed?

2023-11-02 00:49 UTC, 96malhar commented on src/AWS.Messaging/Services/InFlightMetadata.cs
> -    /// <summary>
We are currently starting this handler task and then recording the in-progress `task` as part of the `InFlightMetadata`  
https://github.com/awslabs/aws-dotnet-messaging/blob/770cf84f59054c25c3fdf49f50f1dc5e91a46ee5/src/AWS.Messaging/Services/DefaultMessageManager.cs#L109-L112

However, the status of the handler `task` is never used in the visibility timeout extension logic. Further, for FIFO queues, we want to record all messages into the `InFlightMetadata` but we don't want to start the handler invocation for all messages at once. Thus the `HandlerTask` property was excluded from the `InFlightMetadata`

2023-11-02 00:49 UTC, 96malhar commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +        UpdateActiveMessageCount(-1);
Done

2023-11-02 00:49 UTC, 96malhar commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +        UpdateActiveMessageCount(-1);
Done

2023-11-02 00:50 UTC, 96malhar commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +            await InvokeHandler(message.Envelope, message.Mapping, token);
Added this logic.

2023-11-02 01:05 UTC, 96malhar commented on test/AWS.Messaging.UnitTests/DefaultMessageManagerTests.cs
> +            // The 1 to 4 allows for some instability around the second boundaries
Currently, we are first starting the handler task and then starting the visibility timeout extension - https://github.com/awslabs/aws-dotnet-messaging/blob/770cf84f59054c25c3fdf49f50f1dc5e91a46ee5/src/AWS.Messaging/Services/DefaultMessageManager.cs#L109-L118

With this PR, the order is now reversed and sometimes the visibility was extended 4 times in this test.

2023-11-02 01:22 UTC, 96malhar commented on test/AWS.Messaging.IntegrationTests/SubscriberTests.cs
> +        var errorMessages = inMemoryLogger.Logs.Where(x => x.Message.Contains("Message handling completed unsuccessfully for message"));
This test uses the [ChatMessageHandler_Failed](https://github.com/awslabs/aws-dotnet-messaging/blob/770cf84f59054c25c3fdf49f50f1dc5e91a46ee5/test/AWS.Messaging.IntegrationTests/Handlers/ChatMessageHandler.cs#L46-L60) handler and asserts on the expected log messages when the handler invocation is completed but with a failed status. 

However, we were not adding the `TempStorage` into the service collection because of which an instance of the handler could never be constructed. This led to a premature failure without the handler ever being invoked.

2023-11-02 01:34 UTC, normj requested changes

2023-11-02 01:34 UTC, normj commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +    private void acknowledgeMessage(MessageEnvelope messageEnvelope, CancellationToken token)
Follow .NET convention and start method name with capital "A".

2023-11-02 01:34 UTC, normj commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +                    _logger.LogError("Handler invocation failed for a message belonging to message group '{groupdId}'. Skipping processing of subsequent messages from the same group.", groupId);
Nice to have, could be helpful for debugging to log how many messages didn't get processed. Also include the message id of the message that failed.

2023-11-02 01:34 UTC, normj commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +            _logger.LogError(ex, "An unknown exception occurred while processing message ID {messageId}", messageEnvelope.Id);
Error message suggestion

```
_logger.LogError(ex, "An exception has been thrown from handler {handlerType} processing message {messageId}", subscriberMapping.HandlerType.Name, messageEnvelope.Id);
```

2023-11-02 01:34 UTC, normj commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +            _logger.LogError(handlerTask.Exception, "Message handling failed unexpectedly for message ID {MessageId}", messageEnvelope.Id);
In this error message and the one above for an unsuccessful processing can we include the handler type name in error message like I suggested above.

2023-11-02 02:17 UTC, 96malhar commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +                    _logger.LogError("Handler invocation failed for a message belonging to message group '{groupdId}'. Skipping processing of subsequent messages from the same group.", groupId);
Added this.

2023-11-02 02:17 UTC, 96malhar commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +    private void acknowledgeMessage(MessageEnvelope messageEnvelope, CancellationToken token)
Done

2023-11-02 02:17 UTC, 96malhar commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +            _logger.LogError(ex, "An unknown exception occurred while processing message ID {messageId}", messageEnvelope.Id);
Done

2023-11-02 02:17 UTC, 96malhar commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +            _logger.LogError(handlerTask.Exception, "Message handling failed unexpectedly for message ID {MessageId}", messageEnvelope.Id);
Done

2023-11-02 04:19 UTC, normj approved these changes

2023-11-02 14:40 UTC, ashovlin commented on src/AWS.Messaging.Lambda/Services/DefaultLambdaMessageProcessor.cs
> +    private async Task ProcessInFifoMode(List<ConvertToEnvelopeResult> messageEnvelopResults, CancellationToken token)
nit: Type in "Envelope"

2023-11-02 14:40 UTC, ashovlin commented on src/AWS.Messaging.Lambda/Services/DefaultLambdaMessageProcessor.cs
> +                throw new InvalidOperationException($"This SQS message cannot be processed in FIFO mode because it does not have a valid message group ID");
Should we `LogError` here? Or will something higher up do so?

Ditto for non-Lambda below.

2023-11-02 14:40 UTC, ashovlin commented on src/AWS.Messaging/SQS/SQSMessagePoller.cs
> +            _ = _messageManager.ProcessMessageAsync(result.Envelope, result.Mapping, token);
The `ProcessMessageAsync` call was previously in a `try` with catches for `AWSMessagingException` and `Exception`. 

But now the `ProcessInStandardMode` invocation is after that. Does the `AWSMessagingException` still get swallowed appropriately?

2023-11-02 14:40 UTC, ashovlin commented on src/AWS.Messaging/Services/DefaultMessageManager.cs
> +using System.ComponentModel.DataAnnotations;
Minor, but why is this here? Is it unused?

2023-11-02 14:42 UTC, ashovlin reviewed
Could you also tidy up the internal design doc and move it to the https://github.com/awslabs/aws-dotnet-messaging/tree/main/docs/design folder?

We did explore multiple approaches here, so think it'd be good to open source our thinking.

2023-11-02 18:23 UTC, 96malhar commented
> Could you also tidy up the internal design doc and move it to the https://github.com/awslabs/aws-dotnet-messaging/tree/main/docs/design folder?
> 
> We did explore multiple approaches here, so think it'd be good to open source our thinking.

I'd prefer to do this separately and I've created DOTNET-7269 to track this work.

2023-11-02 19:54 UTC, ashovlin approved these changes

2023-11-02 19:55 UTC, merged