feat: Add OpenTelemetry Instrumentation Provider
awslabs/aws-dotnet-messaging pull request #68
Opened 2023-11-01 16:36 UTC by ashovlin

*Issue #, if available:* DOTNET-7031

*Description of changes:*
* Adds `AWS.Messaging.Telemetry.OpenTelemetry`, which instruments the AWS Message Processing Framework for .NET for OpenTelemetry
    * Based heavily on @normj 's prototype in https://github.com/awslabs/aws-dotnet-messaging/tree/normj/telemetry
* Outside of OTel, the framework will now serialize `MessageEnvelope.Metadata` as top-level properties in the JSON envelope when sending messages. We're using this to telemetry, but us and customers can use for other CloudEvents extensions and/or custom attributes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-01 16:37 UTC, ashovlin commented on sampleapps/PublisherAPI/PublisherAPI.csproj
> +    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.6.0" />
The `OpenTelemetry.Extensions.Hosting` is necessary to use our new `AddAWSMessagingInstrumentation` extension method. Should it just be a dependency of our OTel package?

2023-11-01 16:45 UTC, ashovlin commented on src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryProvider.cs
> +                if (value is JsonElement jsonValue)
Norm's prototype introduced [DictionaryStringObjectConverter](https://github.com/awslabs/aws-dotnet-messaging/blob/normj/telemetry/src/AWS.Messaging/Serialization/DictionaryStringObjectConverter.cs), which was deserializing these back to strings. 

I didn't implement that yet since we'd have to cover a lot of primitive types, so for now customers and us will have to use `JsonElement` and know what type corresponds to which key. Let me know if you'd rather use that approach though.

This also means the `else if` is dead code, had left it in from iterating on tests.

2023-11-01 16:45 UTC, ashovlin commented on src/AWS.Messaging/MessageEnvelope.cs
> +    /// can be used for CloudEvents Extension Attributes.
Curious for your thoughts on this. If we did not want to give customers the ability to do this, we can move telemetry (and any other future use cases) to a `internal PrivateMetadata` member for stuff we do want to serialize, and then `Metadata` will only be used for deserialization like it was previously.

2023-11-01 16:45 UTC, ashovlin commented on test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
> +        var expectedserializedMessage = "eyJpZCI6IjEyMyIsInNvdXJjZSI6Ii9hd3MvbWVzc2FnaW5nIiwic3BlY3ZlcnNpb24iOiIxLjAiLCJ0eXBlIjoiYWRkcmVzc0luZm8iLCJ0aW1lIjoiMjAwMC0xMi0wNVQxMDozMDo1NSswMDowMCIsImRhdG
This is due to the change to now serialize `Metadata` in the outgoing message.

2023-11-01 21:21 UTC, normj requested changes

2023-11-01 21:21 UTC, normj commented on src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryProvider.cs
> +                if (value is JsonElement jsonValue)
I would prefer we do some conversion. It seems confusing to users that in the publish they put in a string or number and then on the subscriber they type has changed. And it feels like we are leaking our serialization logic potentially into user's business code.

2023-11-01 21:21 UTC, normj commented on src/AWS.Messaging.Telemetry.OpenTelemetry/README.md
> +dotnet add package OpenTelemetry.Extensions.Hosting
I'm trying to understand if installing `OpenTelemetry.Extensions.Hosting` is just what you have to do to use OTel. I want to make it clear when we are explaining how to use OTel with .NET and when to do something special for us.

2023-11-01 21:21 UTC, normj commented on src/AWS.Messaging/MessageEnvelope.cs
> +    /// can be used for CloudEvents Extension Attributes.
I do want to give customers the ability to add their own metadata. Maybe though we only need support `string` metadata though. But that gets in the way of the `JsonExtensionData`. Maybe those concerns of application level metadata should be separated from extra deserialized data place holder..

2023-11-01 21:21 UTC, normj commented on src/AWS.Messaging/Serialization/EnvelopeSerializer.cs
> +            foreach (var key in envelope.Metadata.Keys)
Is that your read for Cloud Events that extensions always put their data at the root of the JSON document?

2023-11-09 14:57 UTC, ashovlin commented on sampleapps/PublisherAPI/PublisherAPI.csproj
> +    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.6.0" />
`OpenTelemetry.Extensions.Hosting` enables `IServiceCollection.AddOpenTelemetry`, which is necessary to use our `AddAWSMessagingInstrumentation` extension that registers our `OpenTelemetryProivder` singleton and adds our source name.

But it is not strictly required, since you can also enable OpenTelemetry via `CreateTracerProviderBuilder` like we do in the tests. This is brought in via `OpenTelemetry`, which is a transitive dependency via our new `AWS.Messaging.Telemetry.OpenTelemetry`.
```
using (var tracerProvider = Sdk.CreateTracerProviderBuilder()
           .AddSource(TelemetryKeys.Source)
           .ConfigureResource(resource => resource.AddService("unittest"))
           .AddInMemoryExporter(activities).Build())
{
    await _publisher.PublishAsync(new ChatMessage { MessageDescription = "Test Description" });
}
```

----

So my thinking was that because the user isn't required to configure OTel via DI, we didn't want to require the dependency ourselves.

2023-11-09 15:02 UTC, ashovlin commented on src/AWS.Messaging/Serialization/EnvelopeSerializer.cs
> +            foreach (var key in envelope.Metadata.Keys)
Yeah, from https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/primer.md#json-extensions
> CloudEvent extension attributes are serialized as siblings to the specification defined attributes - meaning, at the top-level of the JSON object. The authors of the specification spent a long time considering all options and decided that this was the best choice.

2023-11-10 16:59 UTC, ashovlin commented on src/AWS.Messaging.Telemetry.OpenTelemetry/README.md
> +dotnet add package OpenTelemetry.Extensions.Hosting
See reply here: https://github.com/awslabs/aws-dotnet-messaging/pull/68#discussion_r1388129171

Added another line to the README explaining why the example is including it, though not absolutely necessary.

2023-11-10 16:59 UTC, ashovlin commented on src/AWS.Messaging/Telemetry/TelemetryKeys.cs
> +    public const string Source = "AWS.Messaging";
Moved.

2023-11-10 17:10 UTC, ashovlin commented on src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryProvider.cs
> +                if (value is JsonElement jsonValue)
I attempted to apply the converter like the prototype, but realized via https://github.com/dotnet/runtime/issues/32903 that a custom `JsonConverter` cannot deserialize the dictionary attributed with `JsonExtensionData` by design.

The prototype was working because it was doing something like this, so that `MessageEnvelope.Metadata` was not being treated as overflow via `JsonExtensionData`
```
{ 
    "metadata": {
         "traceparent": "..."
    } 
}
```

But we want the OTel info (and possibly other extensions, set by us internally or users) in the top of the CloudEvents envelope. 

We had an internal discussion on 11/9/23 debating:
1. Leave deserialization as-is (both us and users will have to work with `JsonElement` values) when handling `Metadata`. We’ll route MPF’s OTel info through this path.
2. Move the OTel properties to real properties in our `MessageEnvelope<T>`  
   * Simplifies this PR since we're not working with overflow, but not user-provided extensions. 
   * We also want to avoid any OTel code in the core `AWS.Messaging` package if possible.
3. We could use `JsonExtensionData` to initially de-serialize overflow into something like `internal RawMetadata<string, JsonElement>` and then do our own copy+casting into a separate `public Metadata<string, object>`.

We agreed to start with approach number 1 for now.

2023-11-10 17:12 UTC, ashovlin commented on src/AWS.Messaging/MessageEnvelope.cs
> +    /// can be used for CloudEvents Extension Attributes.
See https://github.com/awslabs/aws-dotnet-messaging/pull/68#discussion_r1389667763

Customers can add to the envelope-level metadata via `ISerializationCallback`, but for now will have to work with `JsonElement` values.

2023-11-10 18:05 UTC, normj commented on sampleapps/PublisherAPI/PublisherAPI.csproj
> +    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.6.0" />
Lets start without it. Easier to add it then remove it.

2023-11-10 19:09 UTC, normj approved these changes

2023-11-15 14:40 UTC, philasmar commented on src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryProvider.cs
> +    /// Extracts propogation context from a <see cref="MessageEnvelope"/>, meant to be used with <see cref="TextMapPropagator"/>
typo in "propogation" should be "propagation"

2023-11-15 14:40 UTC, philasmar commented on src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryTrace.cs
> +        // propogate the the current activity (if it exists) through the message envelope
you have 2 "the" in a row.

2023-11-15 14:40 UTC, philasmar commented on src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryTrace.cs
> +    private bool _disposed;
nit: add a new line between the property and the summary below

2023-11-15 14:40 UTC, philasmar commented on test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
> +        Assert.Equal(true, envelope.Metadata["Is-Delivered"].GetBoolean());
could you please resolve the warnings?

2023-11-15 21:53 UTC, ashovlin commented on test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
> +        Assert.Equal(true, envelope.Metadata["Is-Delivered"].GetBoolean());
I was taking a small moral stance here, since we weren't really asserting that _"some condition is true"_, rather more like _"this piece of data is equal to the value `true`"_. 

But updated, not a big deal.

2023-11-15 21:53 UTC, ashovlin commented on src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryTrace.cs
> +    private bool _disposed;
Fixed in https://github.com/awslabs/aws-dotnet-messaging/pull/68/commits/759236875251f757e2a10fb90851581e84ce8642

2023-11-15 21:54 UTC, ashovlin commented on src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryTrace.cs
> +        // propogate the the current activity (if it exists) through the message envelope
Fixed in https://github.com/awslabs/aws-dotnet-messaging/pull/68/commits/759236875251f757e2a10fb90851581e84ce8642

2023-11-15 21:54 UTC, ashovlin commented on src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryTrace.cs
> +/// An OpenTelemetry trace (wrapper around a <see cref="Activity"/>
Fixed in https://github.com/awslabs/aws-dotnet-messaging/pull/68/commits/759236875251f757e2a10fb90851581e84ce8642

2023-11-15 21:54 UTC, ashovlin commented on src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryProvider.cs
> +    /// Extracts propogation context from a <see cref="MessageEnvelope"/>, meant to be used with <see cref="TextMapPropagator"/>
Fixed in https://github.com/awslabs/aws-dotnet-messaging/pull/68/commits/759236875251f757e2a10fb90851581e84ce8642

2023-11-16 15:16 UTC, philasmar approved these changes

2023-11-16 17:55 UTC, merged