feat: Add support for specifying the message destination and AWS service client when publishing a specific message.
awslabs/aws-dotnet-messaging pull request #93
Opened 2024-02-05 16:53 UTC by ashovlin

*Issue #, if available:* https://github.com/awslabs/aws-dotnet-messaging/issues/90, DOTNET-7333

*Description of changes:* This adds support for configuring the destination and AWS client at the point of publishing. This may be useful for multi-tenant applications as described in #90 , where the destination of the message (and therefore the credentials required to publish it) aren't known until building the message.

For configuring the publisher without a destination in advance, I considered:
1. A new method, like `AddGenericSQSPublisher`, (or maybe `Destinationless`? `Unknown`?) 
    * **Why not?** Couldn't think of a good name
2. Leaving the signature as is, but requiring users to register a fake destination `AddSQSPublisher("WILL_OVERRIDE_LATER")`
    * **Why not?** Don't want to end up in a state where a user forgets to set the message-specific destination and we're sending requests to a bad/unknown endpoint.
3. Flipping our existing `string queueURL` parameter to `string? queueURL` so allowing `AddSQSPublisher(null)`
     * **Why ?** Seems like a balance between options 1 and 2 above.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-06 01:31 UTC, normj requested changes

2024-02-06 01:31 UTC, normj commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs
> +                var client = _eventBridgeClient;
If a users is only using the `OverrideClient` property then it seems possible there are not environment configuration that the `awsClientProvider.GetServiceClient` will be able to resolve the creation of the service client. The `AWSClientProvider` will throw a `FailedToFindAWSServiceClientException` exception for a service client the user didn't even want. 

I'm guessing the problem exists in all 3 publishers.

2024-02-06 01:31 UTC, normj commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs
> +                    if (client is AmazonServiceClient)
Unfortunately I don't think there is a safe way to add this callback because you need to add only if hasn't already been added to this instance. In your case if the same instance is used for `OverrideClient` then the `AWSServiceClient_BeforeServiceRequest` is added multiple times and called for each time it is added. This callback should generally only be added as part of service client creation not on a per operation situation.

2024-02-07 17:08 UTC, ashovlin commented on src/AWS.Messaging/Configuration/IMessageBusBuilder.cs
> +    IMessageBusBuilder AddSQSPublisher<TMessage>(string? queueUrl, string? messageTypeIdentifier = null);
Expanded in https://github.com/awslabs/aws-dotnet-messaging/pull/93/commits/84282884e9c5f601bb85c2533e36b6f63d7bcf29

2024-02-07 17:08 UTC, ashovlin commented on src/AWS.Messaging/Configuration/IMessageBusBuilder.cs
> +    IMessageBusBuilder AddSNSPublisher<TMessage>(string? topicUrl, string? messageTypeIdentifier = null);
Expanded in https://github.com/awslabs/aws-dotnet-messaging/pull/93/commits/84282884e9c5f601bb85c2533e36b6f63d7bcf29

2024-02-07 17:10 UTC, ashovlin commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs
> +                    if (client is AmazonServiceClient)
Removed the user agent handling after our internal discussion. We lose some future ability to filter these requests based on whether they're coming from the messaging framework vs. the underlying SDK, but we also want to be cautious around manipulating the user-provided clients.

2024-02-07 18:13 UTC, ashovlin commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs
> +                var client = _eventBridgeClient;
Still working on this, but documenting current state. Since `MessageBusBuilder` is still calling `services.TryAddAWSService<Amazon.SQS.IAmazonSQS>()`, even for a destination-less publisher, I don't think we're actually triggering the `FailedToFindAWSServiceClientException`

With no `[default]` credentials or region at all is actually an exception from down in NetCore.Setup, not the `FailedToFindAWSServiceClientException`.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> Amazon.Runtime.AmazonClientException: No RegionEndpoint or ServiceURL configured
         at Amazon.Runtime.ClientConfig.Validate()
         at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config)
         --- End of inner exception stack trace ---
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateClient(Type serviceInterfaceType, AWSCredentials credentials, ClientConfig config)
         at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateServiceClient(ILogger logger, Type serviceInterfaceType, AWSOptions options)
         at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateServiceClient(IServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at AWS.Messaging.Configuration.AWSClientProvider.GetServiceClient[T]() in C:\dev\aws-dotnet-messaging\src\AWS.Messaging\Configuration\AWSClientProvider.cs:line 31
         at AWS.Messaging.Publishers.SQS.SQSPublisher..ctor(IAWSClientProvider awsClientProvider, ILogger`1 logger, IMessageConfiguration messageConfiguration, IEnvelopeSerializer envelopeSerializer, ITelemetryFactory telemetryFactory) in C:\dev\aws-dotnet-messaging\src\AWS.Messaging\Publishers\SQS\SQSPublisher.cs:line 38
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean 
```

With a region but no credentials then we get this from in the SDK
```
Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
    ...
```

2024-02-11 01:53 UTC, normj approved these changes

2024-02-12 16:55 UTC, philasmar approved these changes

2024-02-12 16:55 UTC, philasmar commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs
> +            // Give precendence to the endpoint ID if specified on the message-specific eventBridgeOptions,
nit: typo in "precendence"

2024-02-15 19:22 UTC, ashovlin commented on src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs
> +            // Give precendence to the endpoint ID if specified on the message-specific eventBridgeOptions,
Fixed in https://github.com/awslabs/aws-dotnet-messaging/pull/93/commits/f63889552d886d188961ae759047f5a372447e48

2024-02-15 19:40 UTC, merged