feat: add ability for users to enable data message logging
awslabs/aws-dotnet-messaging pull request #95
Opened 2024-02-09 15:56 UTC by philasmar

*Issue #, if available:*
DOTNET-7340
DOTNET-7342

*Description of changes:*
* Added a new method `EnableDataMessageLogging` in the message bus builder that would enable data messages to be logged as well as appear in any exceptions thrown.
* Added tests, updated the sample apps and README

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-11 01:48 UTC, normj requested changes

2024-02-11 01:48 UTC, normj commented on README.md
> +    builder.EnableDataMessageLogging();
We should have a way for this to be enabled for `IConfiguration` so users can enable this without changing code.

2024-02-11 01:48 UTC, normj commented on src/AWS.Messaging/Configuration/IMessageConfiguration.cs
> +    bool DataMessageLogging { get; set; }
My preference for naming is `LogMessageContent`.

2024-02-11 01:48 UTC, normj commented on src/AWS.Messaging/Serialization/EnvelopeSerializer.cs
> +        catch (JsonException) when (!_messageConfiguration.DataMessageLogging)
Is the idea that if the message is `JsonException` the inner exception might contain the message body? This seems hard to debug if we don't give the user any of the JSON parsing error message.

2024-02-11 01:48 UTC, normj commented on src/AWS.Messaging/Serialization/MessageSerializer.cs
> +        catch (JsonException) when (!_messageConfiguration.DataMessageLogging)
Same question about not giving any information about the JSON parse error.

2024-02-11 01:48 UTC, normj commented on src/AWS.Messaging/Serialization/MessageSerializer.cs
> +        catch (JsonException) when (!_messageConfiguration.DataMessageLogging)
Same question about not giving any information about the JSON parse error.

2024-02-11 01:48 UTC, normj commented on src/AWS.Messaging/Serialization/MessageSerializer.cs
> +                _logger.LogTrace("Serialized the message object to a raw string");
Maybe given them the size of the raw string to they know it is not an empty string or something?

2024-02-12 16:09 UTC, philasmar commented on README.md
> +    builder.EnableDataMessageLogging();
Done

2024-02-12 16:09 UTC, philasmar commented on src/AWS.Messaging/Configuration/IMessageConfiguration.cs
> +    bool DataMessageLogging { get; set; }
Done

2024-02-12 16:09 UTC, philasmar commented on src/AWS.Messaging/Serialization/MessageSerializer.cs
> +                _logger.LogTrace("Serialized the message object to a raw string");
Done

2024-02-12 16:44 UTC, philasmar commented on src/AWS.Messaging/Serialization/EnvelopeSerializer.cs
> +        catch (JsonException) when (!_messageConfiguration.DataMessageLogging)
Yes correct. The PenTester said since we are unsure what content might/will be exposed in the inner exception, then we need to remove or redact this information. The messages I have seen from JsonException are not particularly the most helpful exceptions.

2024-02-12 16:44 UTC, philasmar commented on src/AWS.Messaging/Serialization/MessageSerializer.cs
> +        catch (JsonException) when (!_messageConfiguration.DataMessageLogging)
Yes correct. The PenTester said since we are unsure what content might/will be exposed in the inner exception, then we need to remove or redact this information. The messages I have seen from JsonException are not particularly the most helpful exceptions.

2024-02-12 16:44 UTC, philasmar commented on src/AWS.Messaging/Serialization/MessageSerializer.cs
> +        catch (JsonException) when (!_messageConfiguration.DataMessageLogging)
Yes correct. The PenTester said since we are unsure what content might/will be exposed in the inner exception, then we need to remove or redact this information. The messages I have seen from JsonException are not particularly the most helpful exceptions.

2024-02-14 23:52 UTC, normj requested changes

2024-02-14 23:52 UTC, normj commented on src/AWS.Messaging/Configuration/MessageBusBuilder.cs
> +            _messageConfiguration.LogMessageContent = settings.LogMessageContent ?? false;
This only works if a user is using the `LoadConfigurationFromSettings` method. I think a user should always be able to turn this on without having to change code. Or maybe `LoadConfigurationFromSettings` should always be code and if there is no mapping in `IConfiguration` it wouldn't do anything.

2024-02-15 15:01 UTC, philasmar commented on src/AWS.Messaging/Configuration/MessageBusBuilder.cs
> +            _messageConfiguration.LogMessageContent = settings.LogMessageContent ?? false;
I have added a `LoadConfigurationFromEnvironment` which will be called automatically in the builder. The reason why I did not call `LoadConfigurationFromSettings` automatically (which would've also tackled our issue) is because that method needs access to the IConfiguration service which is not accessible automatically in the MessageBusBuilder.

2024-02-15 16:46 UTC, 96malhar commented on README.md
> +The framework does not log data messages sent by the user for security purposes. If users want to enabled this functionality for debugging purposes, you need to call `EnableDataMessageLogging()` in t
nit: "enabled" -> "enable"

2024-02-15 16:46 UTC, 96malhar commented on src/AWS.Messaging/Configuration/Internal/ApplicationSettings.cs
> +    public bool? LogMessageContent { get; set; } = default;
Should this be nullable? In the `MessageBusBuilder` you are always defaulting to `false` if this value is null.

2024-02-15 18:28 UTC, philasmar commented on README.md
> +The framework does not log data messages sent by the user for security purposes. If users want to enabled this functionality for debugging purposes, you need to call `EnableDataMessageLogging()` in t
Fixed

2024-02-15 18:29 UTC, normj approved these changes

2024-02-15 18:31 UTC, 96malhar commented on src/AWS.Messaging/Configuration/Internal/ApplicationSettings.cs
> +    public bool? LogMessageContent { get; set; } = default;
What I meant was that `LogMessageContent ` should be an non-nullable `bool` in `ApplicationSettings ` as well. That way if a user does not specify any value for it in the `appsettings.json` file, then we end up with an explicit `false` and we'll avoid the null check while setting this property on the `_messageConfiguration`.

![image](https://github.com/awslabs/aws-dotnet-messaging/assets/36622308/78b4369c-80fd-4fef-bc84-f12be5ae1941)

Anyway, this is minor and not a deal breaker.

2024-02-15 18:31 UTC, 96malhar approved these changes

2024-02-15 18:47 UTC, philasmar commented on src/AWS.Messaging/Configuration/Internal/ApplicationSettings.cs
> +    public bool? LogMessageContent { get; set; } = default;
Them not specifying a value for it is not indicative of what the value should be as there are multiple sources for this value. I wanted ApplicationSettings to be indicative of what values were provided.

2024-02-15 18:47 UTC, merged