chore: add validation to the ECS Task Metadata
awslabs/aws-dotnet-messaging pull request #96
Opened 2024-02-14 18:04 UTC by philasmar

*Issue #, if available:*
DOTNET-7341

*Description of changes:*
* Added validation for the ECS Metadata endpoint to look for the IP `169.254.170.2`
* Added a POCO that represents the data returned by the endpoint which adds more validation on the structure of the data
* Added validation to the Cluster and TaskARN returned

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-14 18:05 UTC, philasmar commented on src/AWS.Messaging/Services/ECSContainerMetadataManager.cs
> +            Regex validPattern = new Regex(@"^[A-Za-z0-9\-_]+$");
I am on the fence about the use of RegEx and it's performance impact in this context. Any thoughts?

2024-02-15 00:12 UTC, normj commented on src/AWS.Messaging/Services/ECSContainerMetadataManager.cs
> +            Regex validPattern = new Regex(@"^[A-Za-z0-9\-_]+$");
If I understand this should only ever be called once so it should have negligible performance impact. Also since it should use the `Compiled` option since it is only being used. Not that you are using it but adding that feedback in case another reviewer suggest it.

2024-02-15 00:12 UTC, normj approved these changes

2024-02-15 17:10 UTC, 96malhar requested changes

2024-02-15 17:10 UTC, 96malhar commented on src/AWS.Messaging/Services/ECSContainerMetadataManager.cs
> +                    null;
We should log an error here saying _"Encountered invalid ECS task metadata..."_ before returning `null`.

2024-02-15 17:10 UTC, 96malhar commented on src/AWS.Messaging/Services/ECSContainerMetadataManager.cs
> +                return null;
We should log an error here saying _"Unable to retrieve ECS task metadata..."_ before returning null.

2024-02-15 18:52 UTC, philasmar commented on src/AWS.Messaging/Services/ECSContainerMetadataManager.cs
> +                    null;
Fixed

2024-02-15 18:53 UTC, philasmar commented on src/AWS.Messaging/Services/ECSContainerMetadataManager.cs
> +                return null;
Fixed

2024-02-15 18:58 UTC, 96malhar commented on test/AWS.Messaging.UnitTests/ECSContainerMetadataManagerTests.cs
> +    public async Task GetContainerTaskMetadata_InvalidJsonReturned()
This test would have to be amended since we added additional log messages when then task metadata is missing or invalid.

2024-02-15 19:22 UTC, philasmar commented on test/AWS.Messaging.UnitTests/ECSContainerMetadataManagerTests.cs
> +    public async Task GetContainerTaskMetadata_InvalidJsonReturned()
Fixed

2024-02-15 20:24 UTC, 96malhar approved these changes

2024-02-15 20:34 UTC, merged