#97 Fixed deserializing of EventBridge object body
awslabs/aws-dotnet-messaging pull request #98
Opened 2024-02-16 15:13 UTC by careri

*Issue #97*

*Description of changes:* Deserialize EventBridge body if JsonValueKind.Object

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-17 01:35 UTC, normj requested changes
If you could add a unit test for this scenario that would be great.

2024-02-19 09:44 UTC, careri commented
Hi, unit test added. (The unit test fails with the old code).

2024-02-28 16:20 UTC, philasmar requested changes

2024-02-28 16:20 UTC, philasmar commented on test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
> +        const string eventbridgeSqsEnvelope = "{\"Attributes\":{\"SenderId\":\"AIDAIP3MER2HFHNCCMVD4\",\"ApproximateFirstReceiveTimestamp\":\"1708335393527\",\"ApproximateReceiveCount\":\"1\",\"SentT
Would you please replace any sensitive info with dummy data? I'm particularly worried about "SenderId".

2024-02-28 16:43 UTC, philasmar reviewed
I ran the unit tests and integ tests internally and they pass for the current changes.

2024-03-26 16:57 UTC, 96malhar reviewed
We have fixed this issue via this PR - https://github.com/awslabs/aws-dotnet-messaging/pull/114
It also adds end-to-end tests for EventBridge and SNS.

This PR can be closed.

2024-03-26 16:58 UTC, closed without merging